-- Minimal modern data plane around the real base schema/migration functions.
-- This file is only loaded into the in-memory database by test-database-restore.mjs.
alter table public.workspace_state
  add column version bigint not null default 1,
  add column last_operation_id text,
  add column primary_epoch bigint;
create table public.workspace_state_versions (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  version bigint not null,
  operation_id text,
  primary_epoch bigint,
  state jsonb not null,
  state_bytes bigint not null default 0,
  checksum text,
  created_at timestamptz not null default now(),
  created_by uuid,
  unique(workspace_id, version)
);
create table public.flbp_data_plane (
  workspace_id text primary key references public.workspaces(id) on delete cascade,
  mode text not null check(mode in ('cloud', 'local', 'recovery')),
  node_id text, base_url text, epoch bigint not null default 0,
  lease_expires_at timestamptz, last_heartbeat_at timestamptz,
  last_backup_at timestamptz, updated_at timestamptz not null default now()
);
create table public.flbp_local_operation_log (
  workspace_id text not null references public.workspaces(id),
  operation_id text not null,
  payload jsonb not null,
  primary key(workspace_id,operation_id)
);
create table public.admin_write_lease (
  workspace_id text primary key, holder_id text not null, holder_label text,
  acquired_at timestamptz not null default now(), heartbeat_at timestamptz not null default now(),
  ttl_seconds integer not null default 90
);
create table public.public_workspace_live (
  workspace_id text primary key references public.workspaces(id),
  state jsonb not null default '{}', updated_at timestamptz not null default now()
);
create table public.fanta_teams (
  id uuid primary key, workspace_id text not null references public.workspaces(id),
  name text not null
);
create table public.fanta_rosters (
  id uuid primary key, team_id uuid not null references public.fanta_teams(id) on delete cascade,
  player_id text not null, role text not null check(role in ('captain','defender','starter')),
  unique(team_id,player_id)
);

-- Additional generated-column fixture covers the generic insertion branch.
alter table public.app_settings add column logo_upper text generated always as (upper(logo)) stored;

create sequence public.restore_delete_probe;
create function public.restore_delete_probe_trigger() returns trigger language plpgsql as $$
begin
  perform nextval('public.restore_delete_probe');
  return old;
end;
$$;
create trigger restore_delete_probe after delete on public.app_settings
  for each row execute function public.restore_delete_probe_trigger();
create function public.restore_insert_failure_trigger() returns trigger language plpgsql as $$
begin
  if current_setting('test.restore_insert_failure', true) = 'on' then
    raise exception 'Injected failure after destructive phase';
  end if;
  return new;
end;
$$;
create trigger restore_insert_failure before insert on public.fanta_rosters
  for each row execute function public.restore_insert_failure_trigger();
