import React from 'react';
import {
  AlertTriangle,
  Archive,
  ArrowRightLeft,
  BadgeInfo,
  CheckCircle2,
  ChevronRight,
  Crosshair,
  Link2,
  Medal,
  PencilLine,
  Search,
  Trash2,
  Unlink2,
  UserRound,
} from 'lucide-react';
import type {
  PlayerAliasRelationRow,
  PlayerContributionSourceRow,
  PlayerProfileSnapshot,
  PlayerTitleSourceRow,
} from '../../../../types';
import {
  buildPlayerProfileSnapshot,
  buildPlayerProfileSnapshots,
  getAliasRemovalImpact,
  removePlayerAliasMapping,
} from '../../../../services/playerDataProvenance';
import { deleteHallOfFameEntry, reassignHallOfFameEntry } from '../../../../services/hallOfFameAdmin';
import { BirthDateInput } from '../../BirthDateInput';
import { formatBirthDateDisplay, getPlayerKey, normalizeBirthDateInput, pickPlayerIdentityValue, resolvePlayerKey } from '../../../../services/playerIdentity';
import { updatePlayerProfileIdentity } from '../../../../services/playerProfileAdmin';
import type { DataTabProps } from '../DataTab';
import { AdminDataConfirmModal } from './AdminDataConfirmModal';

type SnackbarState =
  | { tone: 'success' | 'error'; message: string }
  | null;

type PlayerListFilter = 'all' | 'archived' | 'manual' | 'mixed' | 'aliases';
type PlayerListSort = 'impact' | 'titles' | 'canestri' | 'name';

const surfaceClass = 'rounded-[24px] border border-slate-200 bg-white shadow-sm shadow-slate-200/70';
const sectionSurfaceClass = 'rounded-[22px] border border-slate-200 bg-white shadow-sm shadow-slate-200/60';
const subCardClass = 'rounded-[18px] border border-slate-200 bg-slate-50/70';
const ring = 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2';
const inputBase =
  `w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-900 placeholder:text-slate-400 transition focus:border-blue-300 ${ring}`;
const buttonBase =
  `inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition disabled:cursor-not-allowed disabled:border-slate-200 disabled:bg-slate-100 disabled:text-slate-400 ${ring}`;
const secondaryButtonClass = `${buttonBase} border border-slate-200 bg-white text-slate-700 hover:bg-slate-50`;
const primaryButtonClass = `${buttonBase} border border-blue-600 bg-blue-600 text-white shadow-sm shadow-blue-600/20 hover:bg-blue-700`;
const dangerButtonClass = `${buttonBase} border border-rose-200 bg-rose-50 text-rose-700 hover:bg-rose-100 focus-visible:ring-rose-500`;
const chipBase =
  `inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-[11px] font-black transition ${ring}`;

const toneClassByKey = {
  archived: 'border-emerald-200 bg-emerald-50 text-emerald-700',
  manual: 'border-violet-200 bg-violet-50 text-violet-700',
  mixed: 'border-sky-200 bg-sky-50 text-sky-700',
  alias: 'border-amber-200 bg-amber-50 text-amber-700',
  danger: 'border-rose-200 bg-rose-50 text-rose-700',
  warning: 'border-amber-200 bg-amber-50 text-amber-700',
  info: 'border-sky-200 bg-sky-50 text-sky-700',
  neutral: 'border-slate-200 bg-slate-100 text-slate-700',
  success: 'border-emerald-200 bg-emerald-50 text-emerald-700',
  changed: 'border-blue-200 bg-blue-50 text-blue-700',
} as const;

const metricCardClass = 'rounded-[18px] border border-slate-200 bg-slate-50/90 px-4 py-3';

const awardLabel = (type: PlayerTitleSourceRow['type']) => {
  if (type === 'winner') return 'Campioni';
  if (type === 'mvp') return 'MVP';
  if (type === 'top_scorer') return 'Capocannoniere';
  if (type === 'defender') return 'Difensore';
  if (type === 'top_scorer_u25') return 'Capocannoniere U25';
  if (type === 'defender_u25') return 'Difensore U25';
  return type;
};

const profileSourceVariant = (profile: PlayerProfileSnapshot): 'archived' | 'manual' | 'mixed' | 'neutral' => {
  if (profile.hasArchivedData && profile.hasManualData) return 'mixed';
  if (profile.hasArchivedData) return 'archived';
  if (profile.hasManualData) return 'manual';
  return 'neutral';
};

const profileSourceLabel = (profile: PlayerProfileSnapshot) => {
  const variant = profileSourceVariant(profile);
  if (variant === 'mixed') return 'Misto';
  if (variant === 'archived') return 'Archivio';
  if (variant === 'manual') return 'Manuale';
  return 'Solo profilo';
};

const formatTitleStatus = (row: PlayerTitleSourceRow) => {
  if (row.manuallyEdited) return { label: 'Riassegnato', tone: 'changed' as const };
  if (row.sourceAutoGenerated) return { label: 'Automatico', tone: 'neutral' as const };
  return { label: 'Manuale', tone: 'info' as const };
};

const groupContributions = (rows: PlayerContributionSourceRow[]) => ({
  archived: rows.filter((row) => row.sourceType === 'archived_tournament_match'),
  manual: rows.filter((row) => row.sourceType === 'manual_integration'),
});

const SourceBadge: React.FC<{
  label: string;
  tone: keyof typeof toneClassByKey;
  icon?: React.ReactNode;
}> = ({ label, tone, icon }) => (
  <span className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-[11px] font-black ${toneClassByKey[tone]}`}>
    {icon}
    {label}
  </span>
);

const MetricCard: React.FC<{
  label: string;
  value: React.ReactNode;
}> = ({ label, value }) => (
  <div className={metricCardClass}>
    <div className="text-[11px] font-black uppercase tracking-[0.08em] text-slate-500">{label}</div>
    <div className="mt-1 text-lg font-black text-slate-950">{value}</div>
  </div>
);

const EmptyState: React.FC<{
  icon: React.ReactNode;
  title: string;
  body: string;
}> = ({ icon, title, body }) => (
  <div className="px-5 py-8 text-center">
    <div className="mx-auto inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-100 text-slate-400">
      {icon}
    </div>
    <div className="mt-4 text-sm font-black text-slate-800">{title}</div>
    <div className="mt-1 text-xs font-semibold leading-5 text-slate-500">{body}</div>
  </div>
);

const PlayerSection: React.FC<{
  icon: React.ReactNode;
  title: string;
  subtitle: string;
  count: number;
  children: React.ReactNode;
}> = ({ icon, title, subtitle, count, children }) => (
  <details open className={`${sectionSurfaceClass} overflow-hidden group`}>
    <summary className="flex cursor-pointer list-none items-center justify-between gap-4 border-b border-slate-100 px-5 py-4">
      <div className="flex items-start gap-3">
        <div className="inline-flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-100 text-slate-600">
          {icon}
        </div>
        <div>
          <div className="text-base font-black text-slate-950">{title}</div>
          <div className="mt-1 text-xs font-semibold text-slate-500">{subtitle}</div>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[11px] font-black text-slate-600">
          {count}
        </span>
        <ChevronRight className="h-4 w-4 text-slate-400 transition group-open:rotate-90" />
      </div>
    </summary>
    <div className="px-5 py-5">{children}</div>
  </details>
);

export const PlayersSubTab: React.FC<DataTabProps> = ({
  state,
  setState,
  setDataSubTab,
  setDataSelectedTournamentId,
  setDataSelectedMatchId,
  t,
}) => {
  const [search, setSearch] = React.useState('');
  const [listFilter, setListFilter] = React.useState<PlayerListFilter>('all');
  const [sortBy, setSortBy] = React.useState<PlayerListSort>('impact');
  const [selectedPlayerId, setSelectedPlayerId] = React.useState('');
  const [selectedTitleId, setSelectedTitleId] = React.useState('');
  const [selectedAliasId, setSelectedAliasId] = React.useState('');
  const [selectedArchiveTournamentId, setSelectedArchiveTournamentId] = React.useState('');
  const [highlightPlayerId, setHighlightPlayerId] = React.useState('');
  const [snackbar, setSnackbar] = React.useState<SnackbarState>(null);
  const [profileDraftName, setProfileDraftName] = React.useState('');
  const [profileDraftBirthDate, setProfileDraftBirthDate] = React.useState('');
  const [reassignDraft, setReassignDraft] = React.useState<{
    rowId: string;
    entryId: string;
    playerSlotIndex?: number | null;
    nextPlayerName: string;
    nextPlayerBirthDate: string;
  } | null>(null);
  const [titleDeleteTarget, setTitleDeleteTarget] = React.useState<PlayerTitleSourceRow | null>(null);
  const [aliasDeleteTarget, setAliasDeleteTarget] = React.useState<{
    alias: PlayerAliasRelationRow;
    impact: ReturnType<typeof getAliasRemovalImpact>;
  } | null>(null);

  const allProfiles = React.useMemo(() => buildPlayerProfileSnapshots(state), [state]);

  const awardLabelText = React.useCallback((type: PlayerTitleSourceRow['type']) => {
    if (type === 'winner') return t('winner_plural');
    if (type === 'mvp') return 'MVP';
    if (type === 'top_scorer') return t('top_scorers_plural');
    if (type === 'defender') return t('defenders_plural');
    if (type === 'top_scorer_u25') return t('players_award_top_scorer_u25');
    if (type === 'defender_u25') return t('players_award_defender_u25');
    return type;
  }, [t]);

  const profileSourceLabelText = React.useCallback((profile: PlayerProfileSnapshot) => {
    const variant = profileSourceVariant(profile);
    if (variant === 'mixed') return t('players_filter_mixed');
    if (variant === 'archived') return t('players_filter_archived');
    if (variant === 'manual') return t('players_filter_manual');
    return t('players_profile_only');
  }, [t]);

  const titleStatusText = React.useCallback((row: PlayerTitleSourceRow) => {
    if (row.manuallyEdited) return { label: t('players_status_reassigned'), tone: 'changed' as const };
    if (row.sourceAutoGenerated) return { label: t('players_status_auto'), tone: 'neutral' as const };
    return { label: t('players_filter_manual'), tone: 'info' as const };
  }, [t]);

  const filterCounts = React.useMemo(() => {
    const counts = { all: allProfiles.length, archived: 0, manual: 0, mixed: 0, aliases: 0 };
    allProfiles.forEach((profile) => {
      const variant = profileSourceVariant(profile);
      if (variant === 'archived') counts.archived += 1;
      if (variant === 'manual') counts.manual += 1;
      if (variant === 'mixed') counts.mixed += 1;
      if (profile.aliasCount > 0) counts.aliases += 1;
    });
    return counts;
  }, [allProfiles]);

  const profiles = React.useMemo(() => {
    const query = search.trim().toLowerCase();
    let next = allProfiles.filter((profile) => {
      const matchesFilter =
        listFilter === 'all'
          ? true
          : listFilter === 'aliases'
            ? profile.aliasCount > 0
            : listFilter === 'mixed'
              ? profile.hasArchivedData && profile.hasManualData
              : listFilter === 'archived'
                ? profile.hasArchivedData && !profile.hasManualData
                : profile.hasManualData && !profile.hasArchivedData;

      if (!matchesFilter) return false;
      if (!query) return true;
      if (profile.displayName.toLowerCase().includes(query)) return true;
      if (profile.playerId.toLowerCase().includes(query)) return true;
      return profile.aliases.some((alias) => alias.otherLabel.toLowerCase().includes(query) || alias.otherKey.toLowerCase().includes(query));
    });

    next = next.slice().sort((a, b) => {
      if (sortBy === 'name') return a.displayName.localeCompare(b.displayName, 'it', { sensitivity: 'base' });
      if (sortBy === 'titles') {
        const diff = b.totalTitles - a.totalTitles;
        if (diff !== 0) return diff;
      }
      if (sortBy === 'canestri') {
        const diff = b.totalCanestri - a.totalCanestri;
        if (diff !== 0) return diff;
      }
      const scoreA = a.totalTitles * 1000 + a.totalCanestri * 10 + a.totalSoffi;
      const scoreB = b.totalTitles * 1000 + b.totalCanestri * 10 + b.totalSoffi;
      const diff = scoreB - scoreA;
      if (diff !== 0) return diff;
      return a.displayName.localeCompare(b.displayName, 'it', { sensitivity: 'base' });
    });

    return next;
  }, [allProfiles, listFilter, search, sortBy]);

  const selectedProfile = React.useMemo(
    () => (selectedPlayerId ? allProfiles.find((profile) => profile.playerId === selectedPlayerId) || null : null),
    [allProfiles, selectedPlayerId]
  );

  const selectedTitle = React.useMemo(
    () => (selectedProfile && selectedTitleId ? selectedProfile.titles.find((row) => row.id === selectedTitleId) || null : null),
    [selectedProfile, selectedTitleId]
  );

  const selectedAlias = React.useMemo(
    () => (selectedProfile && selectedAliasId ? selectedProfile.aliases.find((row) => row.id === selectedAliasId) || null : null),
    [selectedProfile, selectedAliasId]
  );

  const groupedContributionsBySource = React.useMemo(
    () => groupContributions(selectedProfile?.contributions || []),
    [selectedProfile]
  );

  const archivedTournamentOptions = React.useMemo(() => {
    if (!selectedProfile) return [];
    const items = new Map<string, { id: string; label: string; year?: string | null }>();
    selectedProfile.titles.forEach((row) => {
      if (row.sourceType !== 'archived_tournament' || !row.sourceTournamentId) return;
      items.set(row.sourceTournamentId, {
        id: row.sourceTournamentId,
        label: row.sourceTournamentName || row.tournamentName,
        year: row.year,
      });
    });
    selectedProfile.contributions.forEach((row) => {
      if (row.sourceType !== 'archived_tournament_match' || !row.tournamentId) return;
      items.set(row.tournamentId, {
        id: row.tournamentId,
        label: row.tournamentName || t('players_archived_tournament_fallback'),
        year: row.tournamentYear || null,
      });
    });
    return Array.from(items.values()).sort((a, b) => {
      const yearDiff = Number(b.year || 0) - Number(a.year || 0);
      if (yearDiff !== 0) return yearDiff;
      return a.label.localeCompare(b.label, 'it', { sensitivity: 'base' });
    });
  }, [selectedProfile]);

  const profileSourceCounts = React.useMemo(() => {
    if (!selectedProfile) {
      return { archivedTitles: 0, manualTitles: 0, archivedStats: 0, manualStats: 0 };
    }
    return {
      archivedTitles: selectedProfile.titles.filter((row) => row.sourceType === 'archived_tournament').length,
      manualTitles: selectedProfile.titles.filter((row) => row.sourceType === 'manual').length,
      archivedStats: groupedContributionsBySource.archived.length,
      manualStats: groupedContributionsBySource.manual.length,
    };
  }, [groupedContributionsBySource, selectedProfile]);

  React.useEffect(() => {
    if (!profiles.length) {
      setSelectedPlayerId('');
      return;
    }
    if (!selectedPlayerId || !profiles.some((profile) => profile.playerId === selectedPlayerId)) {
      setSelectedPlayerId(profiles[0].playerId);
    }
  }, [profiles, selectedPlayerId]);

  React.useEffect(() => {
    if (!selectedProfile) {
      setSelectedTitleId('');
      setSelectedAliasId('');
      return;
    }
    if (selectedTitleId && !selectedProfile.titles.some((row) => row.id === selectedTitleId)) setSelectedTitleId('');
    if (selectedAliasId && !selectedProfile.aliases.some((row) => row.id === selectedAliasId)) setSelectedAliasId('');
  }, [selectedAliasId, selectedProfile, selectedTitleId]);

  React.useEffect(() => {
    if (!selectedArchiveTournamentId || !archivedTournamentOptions.some((item) => item.id === selectedArchiveTournamentId)) {
      setSelectedArchiveTournamentId(archivedTournamentOptions[0]?.id || '');
    }
  }, [archivedTournamentOptions, selectedArchiveTournamentId]);

  React.useEffect(() => {
    if (!selectedProfile) {
      setProfileDraftName('');
      setProfileDraftBirthDate('');
      return;
    }
    setProfileDraftName(selectedProfile.displayName || '');
    setProfileDraftBirthDate(/^\d{2}\/\d{2}\/\d{4}$/.test(selectedProfile.yobLabel || '') ? selectedProfile.yobLabel : '');
  }, [selectedProfile]);

  React.useEffect(() => {
    if (!snackbar) return;
    const timer = window.setTimeout(() => setSnackbar(null), 2600);
    return () => window.clearTimeout(timer);
  }, [snackbar]);

  React.useEffect(() => {
    if (!highlightPlayerId) return;
    const timer = window.setTimeout(() => setHighlightPlayerId(''), 1500);
    return () => window.clearTimeout(timer);
  }, [highlightPlayerId]);


  const profileUpdateMeta = React.useMemo(() => {
    if (!selectedProfile) return null;

    const countTeamSlots = (teams: any[] | undefined) => {
      if (!Array.isArray(teams) || !teams.length) return 0;
      return teams.reduce((total, team) => {
        let nextTotal = total;
        const player1Key = team.player1 ? resolvePlayerKey(state, getPlayerKey(team.player1, pickPlayerIdentityValue((team as any).player1BirthDate, team.player1YoB))) : '';
        const player2Key = team.player2 ? resolvePlayerKey(state, getPlayerKey(team.player2, pickPlayerIdentityValue((team as any).player2BirthDate, team.player2YoB))) : '';
        if (player1Key === selectedProfile.playerId) nextTotal += 1;
        if (player2Key === selectedProfile.playerId) nextTotal += 1;
        return nextTotal;
      }, 0);
    };

    const nextName = profileDraftName.trim();
    const nextBirthDate = normalizeBirthDateInput(profileDraftBirthDate) || undefined;
    const currentBirthDate = normalizeBirthDateInput(/^\d{2}\/\d{2}\/\d{4}$/.test(selectedProfile.yobLabel || '') ? selectedProfile.yobLabel : '') || undefined;
    const currentProfile = buildPlayerProfileSnapshot(state, selectedProfile.playerId);
    const nextRawPlayerId = nextName ? getPlayerKey(nextName, pickPlayerIdentityValue(nextBirthDate)) : '';
    const nextPlayerId = nextRawPlayerId ? resolvePlayerKey(state, nextRawPlayerId) : '';
    const targetProfile = nextPlayerId ? buildPlayerProfileSnapshot(state, nextPlayerId) : null;
    const isSameName = selectedProfile.displayName.trim() === nextName;
    const isSameBirthDate = (currentBirthDate || '') === (nextBirthDate || '');
    const hasChanges = !!nextName && (!isSameName || !isSameBirthDate);
    const mergeTarget = !!targetProfile && nextPlayerId !== selectedProfile.playerId;

    return {
      nextName,
      hasChanges,
      mergeTarget,
      targetLabel: targetProfile ? `${targetProfile.displayName}${targetProfile.yobLabel && targetProfile.yobLabel !== 'ND' ? ` · ${targetProfile.yobLabel}` : ''}` : '',
      registeredSlots: countTeamSlots(state.teams),
      liveTournamentSlots: countTeamSlots(state.tournament?.teams),
      archivedTeamSlots: (state.tournamentHistory || []).reduce((total, tournamentRow) => total + countTeamSlots(tournamentRow.teams), 0),
      contributionRows: currentProfile?.contributions.length || 0,
      titleRows: currentProfile?.titles.length || 0,
      aliasCount: currentProfile?.aliasCount || 0,
    };
  }, [profileDraftBirthDate, profileDraftName, selectedProfile, state]);

  const openArchiveFlow = (tournamentId?: string | null) => {
    if (!tournamentId) return;
    setDataSubTab('archive');
    setDataSelectedTournamentId(tournamentId);
    setDataSelectedMatchId('');
    try {
      sessionStorage.setItem('flbp_admin_data_subtab', 'archive');
    } catch {}
  };

  const confirmDeleteTitle = () => {
    if (!titleDeleteTarget) return;
    try {
      const result = deleteHallOfFameEntry(state, titleDeleteTarget.entryId);
      setState(result.state);
      setTitleDeleteTarget(null);
      setReassignDraft(null);
      setHighlightPlayerId(selectedPlayerId);
      setSnackbar({ tone: 'success', message: t('players_snackbar_title_deleted').replace('{title}', awardLabelText(titleDeleteTarget.type)) });
    } catch (error: any) {
      setSnackbar({ tone: 'error', message: error?.message || t('players_snackbar_title_delete_error') });
    }
  };

  const confirmRemoveAlias = () => {
    if (!aliasDeleteTarget) return;
    try {
      setState(removePlayerAliasMapping(state, aliasDeleteTarget.alias.fromKey));
      setAliasDeleteTarget(null);
      setHighlightPlayerId(selectedPlayerId);
      setSnackbar({ tone: 'success', message: t('players_snackbar_alias_removed') });
    } catch (error: any) {
      setSnackbar({ tone: 'error', message: error?.message || t('players_snackbar_alias_remove_error') });
    }
  };

  const applyProfileUpdate = () => {
    if (!selectedProfile) return;
    try {
      const nextState = updatePlayerProfileIdentity(state, {
        currentPlayerId: selectedProfile.playerId,
        nextPlayerName: profileDraftName.trim(),
        nextBirthDate: normalizeBirthDateInput(profileDraftBirthDate) || undefined,
      });
      setState(nextState);
      setHighlightPlayerId(selectedProfile.playerId);
      setSnackbar({ tone: 'success', message: t('players_snackbar_profile_updated') });
    } catch (error: any) {
      setSnackbar({ tone: 'error', message: error?.message || t('players_snackbar_profile_update_error') });
    }
  };

  const applyReassign = () => {
    if (!reassignDraft) return;
    const nextName = reassignDraft.nextPlayerName.trim();
    if (!nextName) {
      setSnackbar({ tone: 'error', message: t('players_snackbar_enter_new_player') });
      return;
    }
    try {
      const result = reassignHallOfFameEntry(state, {
        entryId: reassignDraft.entryId,
        nextPlayerName: nextName,
        nextPlayerBirthDate: normalizeBirthDateInput(reassignDraft.nextPlayerBirthDate) || undefined,
        playerSlotIndex: reassignDraft.playerSlotIndex,
      });
      setState(result.state);
      setHighlightPlayerId(selectedPlayerId);
      setSnackbar({ tone: 'success', message: t('players_snackbar_title_reassigned') });
      setReassignDraft(null);
    } catch (error: any) {
      setSnackbar({ tone: 'error', message: error?.message || t('players_snackbar_title_reassign_error') });
    }
  };

  const quickFilterLabels: Array<{ key: PlayerListFilter; label: string; count: number }> = [
    { key: 'all', label: t('all'), count: filterCounts.all },
    { key: 'archived', label: t('players_filter_archived'), count: filterCounts.archived },
    { key: 'manual', label: t('players_filter_manual'), count: filterCounts.manual },
    { key: 'mixed', label: t('players_filter_mixed'), count: filterCounts.mixed },
    { key: 'aliases', label: t('players_aliases_label'), count: filterCounts.aliases },
  ];

  const selectedTitleStatus = selectedTitle ? titleStatusText(selectedTitle) : null;

  return (
    <>
      <div className="space-y-5">
        <div className={`${surfaceClass} overflow-hidden`}>
          <div className="border-b border-slate-100 px-6 py-5">
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <div className="text-[28px] font-black leading-none text-slate-950">{t('players_tab_title')}</div>
                <div className="mt-2 text-sm font-semibold text-slate-500">
                  {t('players_tab_subtitle')}
                </div>
              </div>
              <div className="flex items-center gap-2">
                <SourceBadge label={t('players_profiles_count').replace('{count}', String(allProfiles.length))} tone="info" icon={<UserRound className="h-3.5 w-3.5" />} />
                <SourceBadge label={t('players_with_aliases_count').replace('{count}', String(filterCounts.aliases))} tone="alias" icon={<Link2 className="h-3.5 w-3.5" />} />
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-5 p-5 xl:grid-cols-[320px_minmax(0,1fr)_340px]">
            <aside className={`${sectionSurfaceClass} overflow-hidden`}>
              <div className="border-b border-slate-100 px-5 py-4">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <div className="text-base font-black text-slate-950">{t('players_list_title')}</div>
                    <div className="mt-1 text-xs font-semibold text-slate-500">{t('players_list_subtitle')}</div>
                  </div>
                  <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[11px] font-black text-slate-600">
                    {profiles.length}
                  </span>
                </div>

                <label className="relative mt-4 block">
                  <Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                  <input
                    aria-label={t('players_search_aria')}
                    value={search}
                    onChange={(event) => setSearch(event.target.value)}
                    placeholder={t('players_search_placeholder')}
                    className={`${inputBase} pl-11 pr-11`}
                  />
                  {search ? (
                    <button
                      type="button"
                      onClick={() => setSearch('')}
                      className={`absolute right-3 top-1/2 -translate-y-1/2 rounded-full border border-slate-200 px-2 py-1 text-[11px] font-black text-slate-500 transition hover:bg-slate-50 ${ring}`}
                    >
                      Pulisci
                    </button>
                  ) : null}
                </label>

                <div className="mt-4 flex flex-wrap gap-2">
                  {quickFilterLabels.map((filter) => {
                    const active = listFilter === filter.key;
                    return (
                      <button
                        key={filter.key}
                        type="button"
                        onClick={() => setListFilter(filter.key)}
                        className={`${chipBase} ${
                          active ? 'border-blue-200 bg-blue-50 text-blue-700' : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'
                        }`}
                        aria-pressed={active}
                      >
                        {filter.label}
                        <span className={`rounded-full px-1.5 py-0.5 ${active ? 'bg-white/80 text-blue-700' : 'bg-slate-100 text-slate-500'}`}>
                          {filter.count}
                        </span>
                      </button>
                    );
                  })}
                </div>

                <div className="mt-4">
                  <label className="text-[11px] font-black uppercase tracking-[0.08em] text-slate-500">{t('players_sort_by')}</label>
                  <select value={sortBy} onChange={(event) => setSortBy(event.target.value as PlayerListSort)} className={`${inputBase} mt-2 py-2.5`}>
                    <option value="impact">{t('players_sort_impact')}</option>
                    <option value="titles">{t('players_sort_titles')}</option>
                    <option value="canestri">{t('players_sort_canestri')}</option>
                    <option value="name">{t('players_sort_name')}</option>
                  </select>
                </div>
              </div>

              <div className="max-h-[980px] space-y-2 overflow-auto px-3 py-3">
                {profiles.map((profile) => {
                  const selected = profile.playerId === selectedPlayerId;
                  const highlighted = profile.playerId === highlightPlayerId;
                  const sourceVariant = profileSourceVariant(profile);
                  return (
                    <button
                      key={profile.playerId}
                      type="button"
                      onClick={() => {
                        setSelectedPlayerId(profile.playerId);
                        setSelectedTitleId('');
                        setSelectedAliasId('');
                        setReassignDraft(null);
                      }}
                      className={`w-full rounded-[20px] border px-4 py-3 text-left transition-all duration-150 ${ring} ${
                        selected
                          ? 'border-blue-200 bg-blue-50 shadow-sm shadow-blue-100 ring-1 ring-blue-100'
                          : 'border-transparent bg-white hover:border-slate-200 hover:bg-slate-50'
                      } ${highlighted ? 'ring-2 ring-emerald-200' : ''}`}
                      aria-current={selected}
                    >
                      <div className="flex items-start gap-3">
                        <div className={`mt-0.5 h-12 w-1.5 rounded-full ${selected ? 'bg-blue-600' : sourceVariant === 'mixed' ? 'bg-sky-300' : 'bg-transparent'}`} />
                        <div className="min-w-0 flex-1">
                          <div className="flex items-start justify-between gap-3">
                            <div className="min-w-0">
                              <div className="text-sm font-black text-slate-950 whitespace-normal break-words leading-tight">{profile.displayName}</div>
                              <div className="mt-1 text-[11px] font-mono text-slate-500 whitespace-normal break-all leading-tight">{profile.playerId}</div>
                            </div>
                            <SourceBadge label={profileSourceLabel(profile)} tone={sourceVariant} />
                          </div>
                          <div className="mt-3 flex flex-wrap gap-2">
                            <SourceBadge label={t('players_titles_count').replace('{count}', String(profile.totalTitles))} tone="info" />
                            <SourceBadge label={t('players_canestri_count').replace('{count}', String(profile.totalCanestri))} tone="archived" />
                            <SourceBadge label={t('players_soffi_count').replace('{count}', String(profile.totalSoffi))} tone="manual" />
                            {profile.aliasCount > 0 ? <SourceBadge label={t('players_alias_count').replace('{count}', String(profile.aliasCount))} tone="alias" /> : null}
                          </div>
                        </div>
                      </div>
                    </button>
                  );
                })}

                {profiles.length === 0 ? (
                  <EmptyState
                    icon={<Search className="h-4 w-4" />}
                    title={t('players_none_found_title')}
                    body={t('players_none_found_body')}
                  />
                ) : null}
              </div>
            </aside>

            <main className="min-w-0 space-y-4">
              {!selectedProfile ? (
                <div className={`${sectionSurfaceClass} p-10`}>
                  <EmptyState
                    icon={<UserRound className="h-5 w-5" />}
                    title={t('players_select_profile_title')}
                    body={t('players_select_profile_body')}
                  />
                </div>
              ) : (
                <>
                  <div className={`${sectionSurfaceClass} overflow-hidden`}>
                    <div className="border-b border-slate-100 px-5 py-5">
                      <div className="flex flex-wrap items-start justify-between gap-4">
                        <div className="min-w-0">
                          <div className="flex flex-wrap items-center gap-2">
                            <div className="text-2xl font-black text-slate-950">{selectedProfile.displayName}</div>
                            <SourceBadge label={profileSourceLabelText(selectedProfile)} tone={profileSourceVariant(selectedProfile)} />
                            {selectedProfile.aliasCount > 0 ? <SourceBadge label={t('players_active_alias')} tone="alias" icon={<Link2 className="h-3.5 w-3.5" />} /> : null}
                          </div>
                          <div className="mt-2 text-xs font-mono text-slate-500">{selectedProfile.playerId}</div>
                          <div className="mt-2 text-sm font-semibold text-slate-500">
                            Profilo canonico con visibilità immediata su titoli, provenienza statistica e unificazioni via alias.
                          </div>
                        </div>
                        <div className="grid min-w-[290px] grid-cols-2 gap-3 md:grid-cols-4">
                          <MetricCard label={t('players_birth_date')} value={selectedProfile.yobLabel} />
                          <MetricCard label={t('players_titles')} value={selectedProfile.totalTitles} />
                          <MetricCard label={t('canestri_tv')} value={selectedProfile.totalCanestri} />
                          <MetricCard label={t('soffi')} value={selectedProfile.totalSoffi} />
                        </div>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-3 px-5 py-4 md:grid-cols-4">
                      <MetricCard label={t('players_aliases_label')} value={selectedProfile.aliasCount} />
                      <MetricCard label={t('players_archive_titles')} value={profileSourceCounts.archivedTitles} />
                      <MetricCard label={t('players_archive_stats')} value={profileSourceCounts.archivedStats} />
                      <MetricCard label={t('players_manual_total')} value={profileSourceCounts.manualTitles + profileSourceCounts.manualStats} />
                    </div>
                  </div>

                  <PlayerSection
                    icon={<Medal className="h-5 w-5" />}
                    title={t('players_titles')}
                    subtitle={t('players_titles_section_subtitle')}
                    count={selectedProfile.titles.length}
                  >
                    <div className="space-y-3">
                      {selectedProfile.titles.map((row) => {
                        const status = formatTitleStatus(row);
                        const selected = selectedTitle?.id === row.id;
                        return (
                          <article
                            key={row.id}
                            className={`rounded-[20px] border p-4 transition ${selected ? 'border-blue-200 bg-blue-50/70 shadow-sm shadow-blue-100' : 'border-slate-200 bg-white hover:border-slate-300'}`}
                          >
                            <div className="flex flex-wrap items-start justify-between gap-4">
                              <button
                                type="button"
                                onClick={() => {
                                  setSelectedTitleId(row.id);
                                  setSelectedAliasId('');
                                }}
                                className={`min-w-0 flex-1 rounded-xl text-left ${ring}`}
                              >
                                <div className="flex flex-wrap items-center gap-2">
                                  <div className="inline-flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-100 text-slate-600">
                                    <Medal className="h-4 w-4" />
                                  </div>
                                  <div className="text-base font-black text-slate-950">{awardLabelText(row.type)}</div>
                                  <SourceBadge label={row.sourceType === 'manual' ? t('players_filter_manual') : t('players_filter_archived')} tone={row.sourceType === 'manual' ? 'manual' : 'archived'} />
                                  <SourceBadge label={status.label} tone={status.tone} />
                                  {selected ? <SourceBadge label={t('players_selected')} tone="changed" /> : null}
                                </div>
                                <div className="mt-3 text-sm font-bold text-slate-900">
                                  {row.tournamentName}
                                  <span className="ml-2 text-slate-500">{row.year}</span>
                                </div>
                                <div className="mt-1 text-xs font-semibold text-slate-500">
                                  tournamentId: <span className="font-mono text-slate-700">{row.tournamentId}</span>
                                  {row.teamName ? <> · squadra: <span className="font-bold text-slate-700">{row.teamName}</span></> : null}
                                  {typeof row.value === 'number' ? <> · valore: <span className="font-bold text-slate-700">{row.value}</span></> : null}
                                </div>
                                <div className="mt-2 text-xs font-semibold text-slate-500">
                                  {row.sourceType === 'manual'
                                    ? t('players_title_manual_desc')
                                    : row.sourceAutoGenerated
                                      ? t('players_title_auto_desc')
                                      : t('players_title_edited_desc')}
                                </div>
                              </button>
                              <div className="flex flex-wrap items-center gap-2">
                                {row.sourceTournamentId ? (
                                  <button type="button" onClick={() => openArchiveFlow(row.sourceTournamentId)} className={secondaryButtonClass}>
                                    <Archive className="h-4 w-4" />
                                    Apri torneo
                                  </button>
                                ) : null}
                                <button
                                  type="button"
                                  onClick={() => {
                                    setSelectedTitleId(row.id);
                                    setSelectedAliasId('');
                                    setReassignDraft({
                                      rowId: row.id,
                                      entryId: row.entryId,
                                      playerSlotIndex: row.playerSlotIndex,
                                      nextPlayerName: '',
                                      nextPlayerBirthDate: '',
                                    });
                                  }}
                                  className={secondaryButtonClass}
                                >
                                  <PencilLine className="h-4 w-4" />
                                  Riassegna
                                </button>
                                <button
                                  type="button"
                                  onClick={() => {
                                    setSelectedTitleId(row.id);
                                    setTitleDeleteTarget(row);
                                  }}
                                  className={dangerButtonClass}
                                >
                                  <Trash2 className="h-4 w-4" />
                                  Elimina
                                </button>
                              </div>
                            </div>
                          </article>
                        );
                      })}
                      {selectedProfile.titles.length === 0 ? (
                        <EmptyState
                          icon={<Medal className="h-4 w-4" />}
                          title={t('players_no_titles_title')}
                          body={t('players_no_titles_body')}
                        />
                      ) : null}
                    </div>
                  </PlayerSection>

                  <PlayerSection
                    icon={<Crosshair className="h-5 w-5" />}
                    title={t('players_stats_by_source_title')}
                    subtitle={t('players_stats_by_source_subtitle')}
                    count={selectedProfile.contributions.length}
                  >
                    <div className="space-y-5">
                      <div className={`${subCardClass} border-emerald-200 bg-emerald-50/50 p-4`}>
                        <div className="flex items-center justify-between gap-3">
                          <div className="flex items-center gap-2">
                            <Archive className="h-4 w-4 text-emerald-700" />
                            <div className="text-sm font-black text-emerald-900">{t('players_archived_tournaments')}</div>
                          </div>
                          <SourceBadge label={t('players_rows_count').replace('{count}', String(groupedContributionsBySource.archived.length))} tone="archived" />
                        </div>
                        <div className="mt-4 space-y-3">
                          {groupedContributionsBySource.archived.map((row) => (
                            <div key={row.id} className="rounded-[18px] border border-emerald-100 bg-white px-4 py-3">
                              <div className="flex flex-wrap items-start justify-between gap-4">
                                <div className="min-w-0">
                                  <div className="flex flex-wrap items-center gap-2">
                                    <div className="text-sm font-black text-slate-950">{row.tournamentName || t('players_archived_tournament_fallback')}</div>
                                    <SourceBadge label={t('players_filter_archived')} tone="archived" />
                                  </div>
                                  <div className="mt-1 text-xs font-semibold text-slate-500">
                                    {row.tournamentYear ? <>Anno: <span className="font-bold text-slate-700">{row.tournamentYear}</span> · </> : null}
                                    {row.matchId ? <>match: <span className="font-mono text-slate-700">{row.matchId}</span> · </> : null}
                                    {row.teamName ? <>squadra: <span className="font-bold text-slate-700">{row.teamName}</span></> : null}
                                  </div>
                                </div>
                                <div className="text-right">
                                  <div className="text-sm font-black text-slate-950">{row.canestri} can</div>
                                  <div className="text-xs font-bold text-slate-500">{row.soffi} soffi</div>
                                </div>
                              </div>
                            </div>
                          ))}
                          {groupedContributionsBySource.archived.length === 0 ? (
                            <EmptyState icon={<Archive className="h-4 w-4" />} title={t('players_no_archive_rows_title')} body={t('players_no_archive_rows_body')} />
                          ) : null}
                        </div>
                      </div>

                      <div className={`${subCardClass} border-violet-200 bg-violet-50/60 p-4`}>
                        <div className="flex items-center justify-between gap-3">
                          <div className="flex items-center gap-2">
                            <PencilLine className="h-4 w-4 text-violet-700" />
                            <div className="text-sm font-black text-violet-900">{t('players_manual_integrations')}</div>
                          </div>
                          <SourceBadge label={t('players_rows_count').replace('{count}', String(groupedContributionsBySource.manual.length))} tone="manual" />
                        </div>
                        <div className="mt-4 space-y-3">
                          {groupedContributionsBySource.manual.map((row) => (
                            <div key={row.id} className="rounded-[18px] border border-violet-100 bg-white px-4 py-3">
                              <div className="flex flex-wrap items-start justify-between gap-4">
                                <div className="min-w-0">
                                  <div className="flex flex-wrap items-center gap-2">
                                    <div className="text-sm font-black text-slate-950">{row.sourceLabel || t('players_added_manually')}</div>
                                    <SourceBadge label={t('players_filter_manual')} tone="manual" />
                                  </div>
                                  <div className="mt-1 text-xs font-semibold text-slate-500">
                                    {row.teamName ? <>squadra: <span className="font-bold text-slate-700">{row.teamName}</span> · </> : null}
                                    {row.games ? <>partite: <span className="font-bold text-slate-700">{row.games}</span> · </> : null}
                                    <span className="font-bold text-violet-700">{t('players_added_manually')}</span>
                                  </div>
                                </div>
                                <div className="text-right">
                                  <div className="text-sm font-black text-slate-950">{row.canestri} can</div>
                                  <div className="text-xs font-bold text-slate-500">{row.soffi} soffi</div>
                                </div>
                              </div>
                            </div>
                          ))}
                          {groupedContributionsBySource.manual.length === 0 ? (
                            <EmptyState icon={<PencilLine className="h-4 w-4" />} title={t('players_no_manual_rows_title')} body={t('players_no_manual_rows_body')} />
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </PlayerSection>

                  <PlayerSection
                    icon={<Link2 className="h-5 w-5" />}
                    title={t('players_aliases_label')}
                    subtitle={t('players_aliases_subtitle')}
                    count={selectedProfile.aliases.length}
                  >
                    <div className="rounded-[18px] border border-amber-200 bg-amber-50/70 px-4 py-3 text-xs font-semibold leading-5 text-amber-900">
                      Gli alias uniscono logicamente i profili nelle classifiche e nei titoli; rimuoverli può separare i dati e redistribuire i record visibili.
                    </div>
                    <div className="mt-4 grid grid-cols-1 gap-3 lg:grid-cols-2">
                      {selectedProfile.aliases.map((aliasRow) => {
                        const selected = selectedAlias?.id === aliasRow.id;
                        return (
                          <article
                            key={aliasRow.id}
                            className={`rounded-[20px] border p-4 transition ${selected ? 'border-amber-200 bg-amber-50 shadow-sm shadow-amber-100' : 'border-slate-200 bg-white hover:border-slate-300'}`}
                          >
                            <div className="flex items-start justify-between gap-4">
                              <button
                                type="button"
                                onClick={() => {
                                  setSelectedAliasId(aliasRow.id);
                                  setSelectedTitleId('');
                                }}
                                className={`min-w-0 flex-1 rounded-xl text-left ${ring}`}
                              >
                                <div className="flex flex-wrap items-center gap-2">
                                  <SourceBadge label={t('players_aliases_label')} tone="alias" icon={<Link2 className="h-3.5 w-3.5" />} />
                                  {selected ? <SourceBadge label={t('players_selected')} tone="changed" /> : null}
                                </div>
                                <div className="mt-3 text-sm font-black text-slate-950">
                                  {aliasRow.fromKey} <span className="text-slate-400">→</span> {aliasRow.toKey}
                                </div>
                                <div className="mt-1 text-xs font-semibold text-slate-500">Direzione: {aliasRow.direction === 'incoming' ? 'from → to' : 'to → from'}</div>
                                <div className="mt-1 text-xs font-semibold text-slate-500">
                                  Profilo collegato: <span className="font-bold text-slate-700">{aliasRow.otherLabel}</span>
                                </div>
                              </button>
                              <button
                                type="button"
                                onClick={() => {
                                  setSelectedAliasId(aliasRow.id);
                                  setAliasDeleteTarget({ alias: aliasRow, impact: getAliasRemovalImpact(state, aliasRow.fromKey) });
                                }}
                                className={dangerButtonClass}
                              >
                                <Unlink2 className="h-4 w-4" />
                                {t('players_remove_alias')}
                              </button>
                            </div>
                          </article>
                        );
                      })}
                    </div>
                    {selectedProfile.aliases.length === 0 ? (
                      <div className="mt-4">
                        <EmptyState icon={<Link2 className="h-4 w-4" />} title={t('players_no_alias_title')} body={t('players_no_alias_body')} />
                      </div>
                    ) : null}
                  </PlayerSection>
                </>
              )}
            </main>

            <aside className="lg:col-span-2 xl:col-span-1 xl:sticky xl:top-24 xl:self-start">
              <div className="space-y-4">
                <div className={`${sectionSurfaceClass} p-5`}>
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <div className="text-base font-black text-slate-950">{t('players_actions_impact_title')}</div>
                      <div className="mt-1 text-xs font-semibold text-slate-500">{t('players_actions_impact_subtitle')}</div>
                    </div>
                    <div className="inline-flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-50 text-blue-700">
                      <BadgeInfo className="h-5 w-5" />
                    </div>
                  </div>

                  {!selectedProfile ? (
                    <div className="mt-5">
                      <EmptyState icon={<BadgeInfo className="h-4 w-4" />} title={t('players_no_actions_title')} body={t('players_no_actions_body')} />
                    </div>
                  ) : (
                    <div className="mt-5 space-y-4">
                      <div className={subCardClass + ' p-4'}>
                        <div className="text-sm font-black text-slate-900">{t('players_fix_profile_title')}</div>
                        <div className="mt-1 text-xs font-semibold text-slate-500">
                          Modifica retroattivamente nome e data di nascita del profilo selezionato. La correzione aggiorna live, referti, classifica, storico e dati derivati dello stesso profilo; se nome e data coincidono con un altro profilo, i dati si accorpano nello stesso playerId.
                        </div>
                        <div className="mt-3 space-y-3">
                          <label className="block">
                            <div className="mb-1 text-[11px] font-black uppercase tracking-[0.08em] text-slate-500">{t('players_correct_name')}</div>
                            <input value={profileDraftName} onChange={(event) => setProfileDraftName(event.target.value)} className={inputBase} placeholder={t('players_name_placeholder')} />
                          </label>
                          <label className="block">
                            <div className="mb-1 text-[11px] font-black uppercase tracking-[0.08em] text-slate-500">{t('players_birth_date')}</div>
                            <BirthDateInput value={profileDraftBirthDate} onChange={setProfileDraftBirthDate} className={inputBase} placeholder={t('players_birth_date_placeholder')} ariaLabel={t('players_profile_birthdate_aria')} />
                          </label>
                          {profileUpdateMeta ? (
                            <div className="space-y-3">
                              <div className="grid grid-cols-2 gap-2 xl:grid-cols-3">
                                <div className="rounded-xl border border-blue-100 bg-white px-3 py-2">
                                  <div className="text-[11px] font-black uppercase tracking-wide text-slate-500">Iscritti live</div>
                                  <div className="mt-1 text-lg font-black text-slate-950">{profileUpdateMeta.registeredSlots}</div>
                                </div>
                                <div className="rounded-xl border border-blue-100 bg-white px-3 py-2">
                                  <div className="text-[11px] font-black uppercase tracking-wide text-slate-500">Torneo live</div>
                                  <div className="mt-1 text-lg font-black text-slate-950">{profileUpdateMeta.liveTournamentSlots}</div>
                                </div>
                                <div className="rounded-xl border border-blue-100 bg-white px-3 py-2">
                                  <div className="text-[11px] font-black uppercase tracking-wide text-slate-500">Storico squadre</div>
                                  <div className="mt-1 text-lg font-black text-slate-950">{profileUpdateMeta.archivedTeamSlots}</div>
                                </div>
                                <div className="rounded-xl border border-blue-100 bg-white px-3 py-2">
                                  <div className="text-[11px] font-black uppercase tracking-wide text-slate-500">Righe statistiche</div>
                                  <div className="mt-1 text-lg font-black text-slate-950">{profileUpdateMeta.contributionRows}</div>
                                </div>
                                <div className="rounded-xl border border-blue-100 bg-white px-3 py-2">
                                  <div className="text-[11px] font-black uppercase tracking-wide text-slate-500">Titoli</div>
                                  <div className="mt-1 text-lg font-black text-slate-950">{profileUpdateMeta.titleRows}</div>
                                </div>
                                <div className="rounded-xl border border-blue-100 bg-white px-3 py-2">
                                  <div className="text-[11px] font-black uppercase tracking-wide text-slate-500">Alias attivi</div>
                                  <div className="mt-1 text-lg font-black text-slate-950">{profileUpdateMeta.aliasCount}</div>
                                </div>
                              </div>

                              {!profileUpdateMeta.nextName ? (
                                <div className="rounded-xl border border-red-200 bg-red-50 px-3 py-3 text-xs font-bold text-red-800">
                                  Inserisci il nome corretto del giocatore per poter salvare.
                                </div>
                              ) : !profileUpdateMeta.hasChanges ? (
                                <div className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs font-bold text-slate-700">
                                  Nessuna modifica effettiva: nome e data coincidono con il profilo attuale.
                                </div>
                              ) : profileUpdateMeta.mergeTarget ? (
                                <div className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-3 text-xs font-bold text-amber-900">
                                  Questa correzione si accorperà al profilo già esistente <span className="font-black">{profileUpdateMeta.targetLabel}</span>. Le occorrenze sopra confluiranno nello stesso playerId, senza duplicare live, referti, classifica, storico o Hall of Fame.
                                </div>
                              ) : (
                                <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-3 text-xs font-bold text-emerald-900">
                                  Questa correzione manterrà separato il profilo dal resto dei dati: le occorrenze sopra verranno aggiornate sul giocatore corretto in live, referti, classifica, storico e Hall of Fame.
                                </div>
                              )}
                            </div>
                          ) : null}
                          <div className="flex items-center gap-2">
                            <button type="button" onClick={applyProfileUpdate} disabled={!selectedProfile || !profileUpdateMeta?.nextName || !profileUpdateMeta?.hasChanges} className={primaryButtonClass}>
                              <CheckCircle2 className="h-4 w-4" />
                              Salva correzione profilo
                            </button>
                          </div>
                        </div>
                      </div>

                      <div className={subCardClass + ' p-4'}>
                        <div className="text-sm font-black text-slate-900">{t('players_quick_actions')}</div>
                        <div className="mt-3 grid grid-cols-1 gap-2">
                          <button
                            type="button"
                            onClick={() => {
                              if (!selectedTitle) return;
                              setReassignDraft({
                                rowId: selectedTitle.id,
                                entryId: selectedTitle.entryId,
                                playerSlotIndex: selectedTitle.playerSlotIndex,
                                nextPlayerName: '',
                                nextPlayerBirthDate: '',
                              });
                            }}
                            disabled={!selectedTitle}
                            className={secondaryButtonClass}
                          >
                            <ArrowRightLeft className="h-4 w-4" />
                            Riassegna titolo selezionato
                          </button>
                          <button type="button" onClick={() => selectedTitle && setTitleDeleteTarget(selectedTitle)} disabled={!selectedTitle} className={dangerButtonClass}>
                            <Trash2 className="h-4 w-4" />
                            {t('players_delete_title')} selezionato
                          </button>
                          <button
                            type="button"
                            onClick={() => {
                              if (!selectedAlias) return;
                              setAliasDeleteTarget({ alias: selectedAlias, impact: getAliasRemovalImpact(state, selectedAlias.fromKey) });
                            }}
                            disabled={!selectedAlias}
                            className={dangerButtonClass}
                          >
                            <Unlink2 className="h-4 w-4" />
                            {t('players_remove_alias')} selezionato
                          </button>
                        </div>
                        {!selectedTitle && !selectedAlias ? (
                          <div className="mt-3 text-xs font-semibold text-slate-500">{t('players_select_detail_action_hint')}</div>
                        ) : null}
                      </div>

                      {reassignDraft ? (
                        <div className="rounded-[20px] border border-blue-200 bg-blue-50/70 p-4">
                          <div className="flex items-center gap-2 text-sm font-black text-blue-900">
                            <PencilLine className="h-4 w-4" />
                            Riassegna titolo
                          </div>
                          <div className="mt-3 space-y-3">
                            <label className="block">
                              <div className="mb-1 text-[11px] font-black uppercase tracking-[0.08em] text-blue-900">{t('players_label_player')}</div>
                              <input
                                value={reassignDraft.nextPlayerName}
                                onChange={(event) => setReassignDraft((current) => (current ? { ...current, nextPlayerName: event.target.value } : current))}
                                className={inputBase}
                                placeholder={t('players_name_placeholder')}
                              />
                            </label>
                            <label className="block">
                              <div className="mb-1 text-[11px] font-black uppercase tracking-[0.08em] text-blue-900">{t('players_birth_date')}</div>
                              <BirthDateInput
                                value={reassignDraft.nextPlayerBirthDate}
                                onChange={(value) =>
                                  setReassignDraft((current) =>
                                    current ? { ...current, nextPlayerBirthDate: value } : current
                                  )
                                }
                                className={inputBase}
                                placeholder={t('players_birth_date_placeholder')}
                                ariaLabel={t('players_reassign_birthdate_aria')}
                              />
                            </label>
                            <div>
                              <div className="mb-2 text-[11px] font-black uppercase tracking-[0.08em] text-blue-900">{t('players_suggested_profiles')}</div>
                              <div className="flex flex-wrap gap-2">
                                {allProfiles
                                  .filter((profile) => profile.playerId !== selectedProfile?.playerId)
                                  .filter((profile) => !reassignDraft.nextPlayerName || profile.displayName.toLowerCase().includes(reassignDraft.nextPlayerName.toLowerCase()))
                                  .slice(0, 8)
                                  .map((profile) => (
                                    <button
                                      key={profile.playerId}
                                      type="button"
                                      onClick={() =>
                                        setReassignDraft((current) =>
                                          current ? { ...current, nextPlayerName: profile.displayName, nextPlayerBirthDate: profile.yobLabel === 'ND' ? '' : profile.yobLabel } : current
                                        )
                                      }
                                      className={`rounded-full border border-blue-200 bg-white px-3 py-1.5 text-[11px] font-black text-blue-700 transition hover:bg-blue-100 ${ring}`}
                                    >
                                      {profile.displayName} ({profile.yobLabel})
                                    </button>
                                  ))}
                              </div>
                            </div>
                            <div className="flex items-center gap-2">
                              <button type="button" onClick={applyReassign} className={primaryButtonClass}>
                                <CheckCircle2 className="h-4 w-4" />
                                {t('players_confirm_reassign')}
                              </button>
                              <button type="button" onClick={() => setReassignDraft(null)} className={secondaryButtonClass}>
                                {t('referees_add_cancel')}
                              </button>
                            </div>
                          </div>
                        </div>
                      ) : null}

                      <div className={subCardClass + ' p-4'}>
                        <div className="text-sm font-black text-slate-900">{t('players_data_origin')}</div>
                        <div className="mt-3 grid grid-cols-2 gap-3">
                          <MetricCard label={t('players_archive_titles')} value={profileSourceCounts.archivedTitles} />
                          <MetricCard label={t('players_manual_titles')} value={profileSourceCounts.manualTitles} />
                          <MetricCard label={t('players_archive_stats')} value={profileSourceCounts.archivedStats} />
                          <MetricCard label={t('players_manual_stats')} value={profileSourceCounts.manualStats} />
                        </div>
                        <div className="mt-4 space-y-2">
                          <SourceBadge label={selectedProfile.hasArchivedData ? t('players_archive_data_present') : t('players_no_archive_data')} tone={selectedProfile.hasArchivedData ? 'archived' : 'neutral'} icon={<Archive className="h-3.5 w-3.5" />} />
                          <SourceBadge label={selectedProfile.hasManualData ? t('players_manual_data_present') : t('players_no_manual_data')} tone={selectedProfile.hasManualData ? 'manual' : 'neutral'} icon={<PencilLine className="h-3.5 w-3.5" />} />
                          {selectedProfile.aliasCount > 0 ? <SourceBadge label={t('players_active_aliases_count').replace('{count}', String(selectedProfile.aliasCount))} tone="alias" icon={<Link2 className="h-3.5 w-3.5" />} /> : null}
                          {selectedTitleStatus ? <SourceBadge label={t('players_selected_title_status').replace('{status}', selectedTitleStatus.label)} tone={selectedTitleStatus.tone} icon={<Medal className="h-3.5 w-3.5" />} /> : null}
                        </div>
                      </div>

                      {archivedTournamentOptions.length ? (
                        <div className={subCardClass + ' p-4'}>
                          <div className="text-sm font-black text-slate-900">{t('players_linked_archive_tournaments')}</div>
                          <div className="mt-1 text-xs font-semibold text-slate-500">
                            {t('players_linked_archive_desc')}
                          </div>
                          <select value={selectedArchiveTournamentId} onChange={(event) => setSelectedArchiveTournamentId(event.target.value)} className={`${inputBase} mt-3 py-2.5`}>
                            {archivedTournamentOptions.map((item) => (
                              <option key={item.id} value={item.id}>
                                {item.label}{item.year ? ` · ${item.year}` : ''}
                              </option>
                            ))}
                          </select>
                          <button type="button" onClick={() => openArchiveFlow(selectedArchiveTournamentId)} className={`${secondaryButtonClass} mt-3 w-full`}>
                            <Archive className="h-4 w-4" />
                            {t('players_go_to_archive_tournament')}
                          </button>
                        </div>
                      ) : null}

                      <div className="rounded-[20px] border border-rose-200 bg-rose-50/70 p-4">
                        <div className="flex items-center gap-2 text-sm font-black text-rose-900">
                          <AlertTriangle className="h-4 w-4" />
                          {t('players_danger_zone_title')}
                        </div>
                        <div className="mt-2 text-xs font-semibold leading-5 text-rose-900/80">
                          {t('players_danger_zone_body')}
                        </div>
                        <div className="mt-4 grid grid-cols-1 gap-2">
                          <button type="button" onClick={() => selectedTitle && setTitleDeleteTarget(selectedTitle)} disabled={!selectedTitle} className={dangerButtonClass}>
                            <Trash2 className="h-4 w-4" />
                            {t('players_delete_title')}
                          </button>
                          <button
                            type="button"
                            onClick={() => {
                              if (!selectedAlias) return;
                              setAliasDeleteTarget({ alias: selectedAlias, impact: getAliasRemovalImpact(state, selectedAlias.fromKey) });
                            }}
                            disabled={!selectedAlias}
                            className={dangerButtonClass}
                          >
                            <Unlink2 className="h-4 w-4" />
                            {t('players_remove_alias')}
                          </button>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </aside>
          </div>
        </div>
      </div>

      <AdminDataConfirmModal
        open={!!titleDeleteTarget}
        tone="danger"
        title={t('players_confirm_delete_title_title')}
        description={t('players_confirm_delete_title_desc')}
        confirmLabel={t('players_delete_title')}
        onClose={() => setTitleDeleteTarget(null)}
        onConfirm={confirmDeleteTitle}
        summaryItems={
          titleDeleteTarget
            ? [
                { label: t('players_modal_title_label'), value: awardLabelText(titleDeleteTarget.type) },
                { label: t('players_modal_tournament_label'), value: titleDeleteTarget.tournamentName },
                { label: t('year'), value: titleDeleteTarget.year },
                { label: t('players_modal_origin_label'), value: titleDeleteTarget.sourceType === 'manual' ? t('players_filter_manual') : t('players_filter_archived') },
              ]
            : []
        }
      >
        <p>{t('players_confirm_delete_title_body')}</p>
      </AdminDataConfirmModal>

      <AdminDataConfirmModal
        open={!!aliasDeleteTarget}
        tone="warning"
        title={t('players_confirm_remove_alias_title')}
        description={t('players_confirm_remove_alias_desc')}
        confirmLabel={t('players_remove_alias')}
        onClose={() => setAliasDeleteTarget(null)}
        onConfirm={confirmRemoveAlias}
        summaryItems={
          aliasDeleteTarget
            ? [
                { label: t('players_aliases_label'), value: `${aliasDeleteTarget.impact.sourceLabel} → ${aliasDeleteTarget.impact.targetLabel}` },
                { label: t('players_modal_separated_profiles'), value: aliasDeleteTarget.impact.separatedProfiles },
                { label: t('players_modal_contribution_rows'), value: aliasDeleteTarget.impact.affectedContributionRows },
                { label: t('players_modal_title_rows'), value: aliasDeleteTarget.impact.affectedTitleRows },
              ]
            : []
        }
      >
        <p>{t('players_confirm_remove_alias_body')}</p>
      </AdminDataConfirmModal>

      {snackbar ? (
        <div className="fixed bottom-5 right-5 z-[95]" role="status" aria-live="polite">
          <div
            className={`min-w-[300px] max-w-[440px] rounded-2xl border px-4 py-3 shadow-xl shadow-slate-900/10 ${
              snackbar.tone === 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-rose-200 bg-rose-50 text-rose-900'
            }`}
          >
            <div className="flex items-start gap-3">
              <div className="mt-0.5 inline-flex h-8 w-8 items-center justify-center rounded-xl bg-white/70">
                {snackbar.tone === 'success' ? <CheckCircle2 className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}
              </div>
              <div className="text-sm font-black">{snackbar.message}</div>
            </div>
          </div>
        </div>
      ) : null}
    </>
  );
};
