-- Additive metadata: no tournament records, matches or identities are migrated.
begin;
alter table public.hall_of_fame_entries
  add column if not exists player_ids text[],
  add column if not exists player_birth_dates text[],
  add column if not exists source_tournament_date text;
alter table public.public_hall_of_fame_entries add column if not exists source_tournament_date text;
alter table public.integrations_scorers add column if not exists source_tournament_date text;
-- These private columns stay under the table's existing admin RLS policies.
create or replace function public.flbp_local_sync_hof_internal(
  p_workspace_id text,
  p_state jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id text := coalesce(nullif(trim(p_workspace_id), ''), 'default');
  v_state jsonb := coalesce(p_state, '{}'::jsonb);
  v_entry jsonb;
  v_player_names text[];
  v_value integer;
  v_count integer := 0;
begin
  if jsonb_typeof(v_state -> 'hallOfFame') <> 'array' then return 0; end if;

  delete from public.hall_of_fame_entries where workspace_id = v_workspace_id;
  delete from public.public_hall_of_fame_entries where workspace_id = v_workspace_id;

  for v_entry in select value from jsonb_array_elements(v_state -> 'hallOfFame')
  loop
    if nullif(trim(coalesce(v_entry ->> 'id', '')), '') is null then continue; end if;
    if coalesce(v_entry ->> 'type', '') not in (
      'winner', 'top_scorer', 'defender', 'mvp', 'top_scorer_u25', 'defender_u25'
    ) then continue; end if;

    v_player_names := case
      when jsonb_typeof(v_entry -> 'playerNames') = 'array'
        then array(select jsonb_array_elements_text(v_entry -> 'playerNames'))
      else '{}'::text[]
    end;
    v_value := case
      when coalesce(v_entry ->> 'value', '') ~ '^-?[0-9]+$' then (v_entry ->> 'value')::integer
      else null
    end;

    insert into public.hall_of_fame_entries (
      workspace_id, id, year, tournament_id, tournament_name, type,
      team_name, player_names, value, player_id, player_birth_date, player_ids, player_birth_dates, source_tournament_date,
      source_type, source_tournament_id, source_tournament_name,
      source_match_id, source_auto_generated, reassigned_from_player_id,
      manually_edited, created_at
    ) values (
      v_workspace_id,
      v_entry ->> 'id',
      coalesce(nullif(v_entry ->> 'year', ''), extract(year from now())::text),
      coalesce(v_entry ->> 'tournamentId', ''),
      coalesce(v_entry ->> 'tournamentName', ''),
      v_entry ->> 'type',
      nullif(v_entry ->> 'teamName', ''),
      v_player_names,
      v_value,
      nullif(v_entry ->> 'playerId', ''),
      case when coalesce(v_entry ->> 'playerBirthDate', '') ~ '^\d{4}-\d{2}-\d{2}$'
        then (v_entry ->> 'playerBirthDate')::date else null end,
      case when jsonb_typeof(v_entry -> 'playerIds') = 'array' then array(select jsonb_array_elements_text(v_entry -> 'playerIds')) else null end,
      case when jsonb_typeof(v_entry -> 'playerBirthDates') = 'array' then array(select jsonb_array_elements_text(v_entry -> 'playerBirthDates')) else null end,
      nullif(v_entry ->> 'sourceTournamentDate', ''),
      nullif(v_entry ->> 'sourceType', ''),
      nullif(v_entry ->> 'sourceTournamentId', ''),
      nullif(v_entry ->> 'sourceTournamentName', ''),
      nullif(v_entry ->> 'sourceMatchId', ''),
      case when v_entry ? 'sourceAutoGenerated'
        then lower(coalesce(v_entry ->> 'sourceAutoGenerated', 'false')) in ('true', 't', '1') else null end,
      nullif(v_entry ->> 'reassignedFromPlayerId', ''),
      case when v_entry ? 'manuallyEdited'
        then lower(coalesce(v_entry ->> 'manuallyEdited', 'false')) in ('true', 't', '1') else null end,
      now()
    )
    on conflict (id) do update set
      workspace_id = excluded.workspace_id,
      year = excluded.year,
      tournament_id = excluded.tournament_id,
      tournament_name = excluded.tournament_name,
      type = excluded.type,
      team_name = excluded.team_name,
      player_names = excluded.player_names,
      value = excluded.value,
      player_id = excluded.player_id,
      player_birth_date = excluded.player_birth_date,
      player_ids = excluded.player_ids,
      player_birth_dates = excluded.player_birth_dates,
      source_tournament_date = excluded.source_tournament_date,
      source_type = excluded.source_type,
      source_tournament_id = excluded.source_tournament_id,
      source_tournament_name = excluded.source_tournament_name,
      source_match_id = excluded.source_match_id,
      source_auto_generated = excluded.source_auto_generated,
      reassigned_from_player_id = excluded.reassigned_from_player_id,
      manually_edited = excluded.manually_edited;

    insert into public.public_hall_of_fame_entries (
      workspace_id, id, year, tournament_id, tournament_name, type,
      team_name, player_names, value, source_type, source_tournament_id,
      source_tournament_name, source_tournament_date, source_auto_generated, manually_edited, created_at
    ) values (
      v_workspace_id,
      v_entry ->> 'id',
      coalesce(nullif(v_entry ->> 'year', ''), extract(year from now())::text),
      coalesce(v_entry ->> 'tournamentId', ''),
      coalesce(v_entry ->> 'tournamentName', ''),
      v_entry ->> 'type',
      nullif(v_entry ->> 'teamName', ''),
      v_player_names,
      v_value,
      nullif(v_entry ->> 'sourceType', ''),
      nullif(v_entry ->> 'sourceTournamentId', ''),
      nullif(v_entry ->> 'sourceTournamentName', ''),
      nullif(v_entry ->> 'sourceTournamentDate', ''),
      case when v_entry ? 'sourceAutoGenerated'
        then lower(coalesce(v_entry ->> 'sourceAutoGenerated', 'false')) in ('true', 't', '1') else null end,
      case when v_entry ? 'manuallyEdited'
        then lower(coalesce(v_entry ->> 'manuallyEdited', 'false')) in ('true', 't', '1') else null end,
      now()
    )
    on conflict (workspace_id, id) do update set
      year = excluded.year,
      tournament_id = excluded.tournament_id,
      tournament_name = excluded.tournament_name,
      type = excluded.type,
      team_name = excluded.team_name,
      player_names = excluded.player_names,
      value = excluded.value,
      source_type = excluded.source_type,
      source_tournament_id = excluded.source_tournament_id,
      source_tournament_name = excluded.source_tournament_name,
      source_tournament_date = excluded.source_tournament_date,
      source_auto_generated = excluded.source_auto_generated,
      manually_edited = excluded.manually_edited;

    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;
revoke all on function public.flbp_local_sync_hof_internal(text, jsonb) from public, anon, authenticated;
commit;
