-- Repair the current Fanta archive routine and make local full-state commits
-- project Hall of Fame awards plus final Fanta rosters atomically.

do $$
declare
  v_definition text;
begin
  select statements[15]
  into v_definition
  from supabase_migrations.schema_migrations
  where version = '20260704000110';

  if v_definition is null
    or position('flbp_archive_fanta_tournament_internal' in v_definition) = 0
    or position('fanta_archived_rosters' in v_definition) = 0
  then
    raise exception 'Definizione Fanta archivio 20260704000110 non disponibile';
  end if;

  execute v_definition;
end;
$$;

create or replace function public.flbp_local_sync_hof_internal(
  p_workspace_id text,
  p_state jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id text := coalesce(nullif(trim(p_workspace_id), ''), 'default');
  v_state jsonb := coalesce(p_state, '{}'::jsonb);
  v_entry jsonb;
  v_player_names text[];
  v_value integer;
  v_count integer := 0;
begin
  if jsonb_typeof(v_state -> 'hallOfFame') <> 'array' then return 0; end if;

  delete from public.hall_of_fame_entries where workspace_id = v_workspace_id;
  delete from public.public_hall_of_fame_entries where workspace_id = v_workspace_id;

  for v_entry in select value from jsonb_array_elements(v_state -> 'hallOfFame')
  loop
    if nullif(trim(coalesce(v_entry ->> 'id', '')), '') is null then continue; end if;
    if coalesce(v_entry ->> 'type', '') not in (
      'winner', 'top_scorer', 'defender', 'mvp', 'top_scorer_u25', 'defender_u25'
    ) then continue; end if;

    v_player_names := case
      when jsonb_typeof(v_entry -> 'playerNames') = 'array'
        then array(select jsonb_array_elements_text(v_entry -> 'playerNames'))
      else '{}'::text[]
    end;
    v_value := case
      when coalesce(v_entry ->> 'value', '') ~ '^-?[0-9]+$' then (v_entry ->> 'value')::integer
      else null
    end;

    insert into public.hall_of_fame_entries (
      workspace_id, id, year, tournament_id, tournament_name, type,
      team_name, player_names, value, player_id, player_birth_date,
      source_type, source_tournament_id, source_tournament_name,
      source_match_id, source_auto_generated, reassigned_from_player_id,
      manually_edited, created_at
    ) values (
      v_workspace_id,
      v_entry ->> 'id',
      coalesce(nullif(v_entry ->> 'year', ''), extract(year from now())::text),
      coalesce(v_entry ->> 'tournamentId', ''),
      coalesce(v_entry ->> 'tournamentName', ''),
      v_entry ->> 'type',
      nullif(v_entry ->> 'teamName', ''),
      v_player_names,
      v_value,
      nullif(v_entry ->> 'playerId', ''),
      case when coalesce(v_entry ->> 'playerBirthDate', '') ~ '^\d{4}-\d{2}-\d{2}$'
        then (v_entry ->> 'playerBirthDate')::date else null end,
      nullif(v_entry ->> 'sourceType', ''),
      nullif(v_entry ->> 'sourceTournamentId', ''),
      nullif(v_entry ->> 'sourceTournamentName', ''),
      nullif(v_entry ->> 'sourceMatchId', ''),
      case when v_entry ? 'sourceAutoGenerated'
        then lower(coalesce(v_entry ->> 'sourceAutoGenerated', 'false')) in ('true', 't', '1') else null end,
      nullif(v_entry ->> 'reassignedFromPlayerId', ''),
      case when v_entry ? 'manuallyEdited'
        then lower(coalesce(v_entry ->> 'manuallyEdited', 'false')) in ('true', 't', '1') else null end,
      now()
    )
    on conflict (id) do update set
      workspace_id = excluded.workspace_id,
      year = excluded.year,
      tournament_id = excluded.tournament_id,
      tournament_name = excluded.tournament_name,
      type = excluded.type,
      team_name = excluded.team_name,
      player_names = excluded.player_names,
      value = excluded.value,
      player_id = excluded.player_id,
      player_birth_date = excluded.player_birth_date,
      source_type = excluded.source_type,
      source_tournament_id = excluded.source_tournament_id,
      source_tournament_name = excluded.source_tournament_name,
      source_match_id = excluded.source_match_id,
      source_auto_generated = excluded.source_auto_generated,
      reassigned_from_player_id = excluded.reassigned_from_player_id,
      manually_edited = excluded.manually_edited;

    insert into public.public_hall_of_fame_entries (
      workspace_id, id, year, tournament_id, tournament_name, type,
      team_name, player_names, value, source_type, source_tournament_id,
      source_tournament_name, source_auto_generated, manually_edited, created_at
    ) values (
      v_workspace_id,
      v_entry ->> 'id',
      coalesce(nullif(v_entry ->> 'year', ''), extract(year from now())::text),
      coalesce(v_entry ->> 'tournamentId', ''),
      coalesce(v_entry ->> 'tournamentName', ''),
      v_entry ->> 'type',
      nullif(v_entry ->> 'teamName', ''),
      v_player_names,
      v_value,
      nullif(v_entry ->> 'sourceType', ''),
      nullif(v_entry ->> 'sourceTournamentId', ''),
      nullif(v_entry ->> 'sourceTournamentName', ''),
      case when v_entry ? 'sourceAutoGenerated'
        then lower(coalesce(v_entry ->> 'sourceAutoGenerated', 'false')) in ('true', 't', '1') else null end,
      case when v_entry ? 'manuallyEdited'
        then lower(coalesce(v_entry ->> 'manuallyEdited', 'false')) in ('true', 't', '1') else null end,
      now()
    )
    on conflict (workspace_id, id) do update set
      year = excluded.year,
      tournament_id = excluded.tournament_id,
      tournament_name = excluded.tournament_name,
      type = excluded.type,
      team_name = excluded.team_name,
      player_names = excluded.player_names,
      value = excluded.value,
      source_type = excluded.source_type,
      source_tournament_id = excluded.source_tournament_id,
      source_tournament_name = excluded.source_tournament_name,
      source_auto_generated = excluded.source_auto_generated,
      manually_edited = excluded.manually_edited;

    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

revoke all on function public.flbp_local_sync_hof_internal(text, jsonb) from public, anon, authenticated;

create or replace function public.flbp_local_refresh_archived_fanta_internal(
  p_workspace_id text,
  p_tournament_id text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id text := coalesce(nullif(trim(p_workspace_id), ''), 'default');
  v_tournament_id text := nullif(trim(p_tournament_id), '');
begin
  if v_tournament_id is null then return false; end if;
  if not exists (
    select 1 from public.fanta_teams
    where workspace_id = v_workspace_id and tournament_id = v_tournament_id
  ) then return false; end if;

  update public.tournaments set status = 'live'
  where workspace_id = v_workspace_id and id = v_tournament_id;
  update public.public_tournaments set status = 'live'
  where workspace_id = v_workspace_id and id = v_tournament_id;

  begin
    perform public.flbp_archive_fanta_tournament_internal(v_workspace_id, v_tournament_id);
  exception when others then
    update public.tournaments set status = 'archived'
    where workspace_id = v_workspace_id and id = v_tournament_id;
    update public.public_tournaments set status = 'archived'
    where workspace_id = v_workspace_id and id = v_tournament_id;
    raise;
  end;

  update public.tournaments set status = 'archived'
  where workspace_id = v_workspace_id and id = v_tournament_id;
  update public.public_tournaments set status = 'archived'
  where workspace_id = v_workspace_id and id = v_tournament_id;
  return true;
end;
$$;

revoke all on function public.flbp_local_refresh_archived_fanta_internal(text, text) from public, anon, authenticated;

create or replace function public.flbp_local_sync_full_normalized_internal(
  p_workspace_id text,
  p_state jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id text := coalesce(nullif(trim(p_workspace_id), ''), 'default');
  v_state jsonb := coalesce(p_state, '{}'::jsonb);
  v_live_result jsonb;
  v_archived jsonb;
  v_archived_state jsonb;
  v_matches jsonb;
  v_tournament_id text;
  v_archived_count integer := 0;
  v_fanta_count integer := 0;
  v_hof_count integer := 0;
begin
  v_live_result := public.flbp_local_sync_live_normalized_internal(v_workspace_id, v_state);

  if jsonb_typeof(v_state -> 'tournamentHistory') = 'array' then
    for v_archived in select value from jsonb_array_elements(v_state -> 'tournamentHistory')
    loop
      v_tournament_id := nullif(trim(coalesce(v_archived ->> 'id', '')), '');
      if v_tournament_id is null then continue; end if;
      v_matches := case
        when jsonb_typeof(v_archived -> 'matches') = 'array'
          and jsonb_array_length(v_archived -> 'matches') > 0 then v_archived -> 'matches'
        when jsonb_typeof(v_archived -> 'rounds') = 'array'
          then jsonb_path_query_array(v_archived, '$.rounds[*][*]')
        else '[]'::jsonb
      end;
      v_archived_state := jsonb_set(v_state, '{tournament}', v_archived, true);
      v_archived_state := jsonb_set(v_archived_state, '{tournamentMatches}', v_matches, true);
      perform public.flbp_local_sync_live_normalized_internal(v_workspace_id, v_archived_state);
      update public.tournaments set status = 'archived', updated_at = now()
      where workspace_id = v_workspace_id and id = v_tournament_id;
      update public.public_tournaments set status = 'archived', updated_at = now()
      where workspace_id = v_workspace_id and id = v_tournament_id;
      v_archived_count := v_archived_count + 1;
    end loop;
  end if;

  v_hof_count := public.flbp_local_sync_hof_internal(v_workspace_id, v_state);

  if jsonb_typeof(v_state -> 'tournamentHistory') = 'array' then
    for v_archived in select value from jsonb_array_elements(v_state -> 'tournamentHistory')
    loop
      v_tournament_id := nullif(trim(coalesce(v_archived ->> 'id', '')), '');
      if v_tournament_id is not null
        and public.flbp_local_refresh_archived_fanta_internal(v_workspace_id, v_tournament_id)
      then
        v_fanta_count := v_fanta_count + 1;
      end if;
    end loop;
  end if;

  return jsonb_build_object(
    'ok', true,
    'live', v_live_result,
    'archived_tournaments', v_archived_count,
    'hall_of_fame', v_hof_count,
    'fanta_archives', v_fanta_count
  );
end;
$$;

revoke all on function public.flbp_local_sync_full_normalized_internal(text, jsonb) from public, anon, authenticated;
