-- FLBP Manager Suite - local tournament data plane + durable version history.
--
-- Invariants:
-- 1. exactly one writable data plane per workspace (cloud or local epoch);
-- 2. an expired local leader enters recovery, never automatic writable cloud;
-- 3. every workspace snapshot change is versioned and recoverable;
-- 4. local operations are idempotent and mirrored as an append-only outbox;
-- 5. service_role is the only identity allowed to coordinate/backup a local node.

alter table public.workspace_state
  add column if not exists version bigint not null default 1,
  add column if not exists last_operation_id text,
  add column if not exists primary_epoch bigint;

create table if not exists public.workspace_state_versions (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  version bigint not null,
  operation_id text,
  primary_epoch bigint,
  state jsonb not null,
  state_bytes bigint not null default 0,
  checksum text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  unique (workspace_id, version)
);

alter table public.workspace_state_versions enable row level security;
revoke all on table public.workspace_state_versions from public, anon, authenticated;

create or replace function public.flbp_workspace_state_before_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text := coalesce(auth.role(), '');
  v_plane record;
  v_backup_context text := coalesce(current_setting('flbp.local_backup_context', true), '');
  v_workspace_id text;
begin
  v_workspace_id := case when tg_op = 'DELETE' then old.workspace_id else new.workspace_id end;
  -- Serializza ogni write cloud con activate/deactivate del data plane. Una
  -- transazione iniziata durante lo switch attende il lock e poi vede il
  -- nuovo mode, invece di attraversare la finestra tra pull e leadership.
  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || v_workspace_id));
  select mode, node_id, epoch, lease_expires_at
  into v_plane
  from public.flbp_data_plane
  where workspace_id = v_workspace_id;

  if found and v_plane.mode in ('local', 'recovery') then
    -- La service role da sola non è un lasciapassare: solo la RPC di backup
    -- che ha verificato node_id + epoch imposta questo contesto transazionale.
    if v_role <> 'service_role'
      or v_backup_context <> (v_workspace_id || ':' || v_plane.node_id || ':' || v_plane.epoch::text)
    then
      if v_plane.mode = 'local' and v_plane.lease_expires_at > now() then
      raise exception 'FLBP_LOCAL_PRIMARY: il server locale è il nodo di scrittura attivo'
        using detail = jsonb_build_object(
          'node_id', v_plane.node_id,
          'epoch', v_plane.epoch,
          'lease_expires_at', v_plane.lease_expires_at
        )::text;
      else
      raise exception 'FLBP_DATA_PLANE_RECOVERY: leadership locale scaduta; le scritture restano sospese fino al recupero esplicito'
        using detail = jsonb_build_object('epoch', v_plane.epoch)::text;
      end if;
    end if;
  end if;

  if tg_op = 'UPDATE' and new.state is distinct from old.state then
    if new.version is null or new.version <= old.version then
      new.version := old.version + 1;
    end if;
    if nullif(trim(coalesce(new.last_operation_id, '')), '') is null
      or new.last_operation_id = old.last_operation_id
    then
      new.last_operation_id := 'legacy-' || md5(clock_timestamp()::text || random()::text);
    end if;
  elsif tg_op = 'INSERT' then
    new.version := greatest(coalesce(new.version, 1), 1);
    if nullif(trim(coalesce(new.last_operation_id, '')), '') is null then
      new.last_operation_id := 'initial-' || md5(clock_timestamp()::text || random()::text);
    end if;
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

-- Created before the trigger function is first executed. PostgreSQL resolves
-- the referenced table at function execution time, so the declaration order
-- remains migration-safe.
create table if not exists public.flbp_data_plane (
  workspace_id text primary key references public.workspaces(id) on delete cascade,
  mode text not null default 'cloud' check (mode in ('cloud', 'local', 'recovery')),
  node_id text,
  base_url text,
  epoch bigint not null default 0,
  lease_expires_at timestamptz,
  last_heartbeat_at timestamptz,
  last_backup_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint flbp_data_plane_local_fields check (
    mode <> 'local' or (node_id is not null and base_url is not null and lease_expires_at is not null)
  )
);

alter table public.flbp_data_plane enable row level security;
drop policy if exists flbp_data_plane_public_read on public.flbp_data_plane;
create policy flbp_data_plane_public_read on public.flbp_data_plane
  for select to anon, authenticated using (true);
grant select on public.flbp_data_plane to anon, authenticated;
revoke insert, update, delete on public.flbp_data_plane from anon, authenticated;

drop trigger if exists flbp_workspace_state_before_write on public.workspace_state;
create trigger flbp_workspace_state_before_write
before insert or update or delete on public.workspace_state
for each row execute function public.flbp_workspace_state_before_write();

create or replace function public.flbp_workspace_state_capture_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.state is distinct from old.state then
    insert into public.workspace_state_versions (
      workspace_id, version, operation_id, primary_epoch, state,
      state_bytes, checksum, created_at, created_by
    ) values (
      new.workspace_id,
      new.version,
      new.last_operation_id,
      new.primary_epoch,
      new.state,
      octet_length(new.state::text),
      md5(new.state::text),
      new.updated_at,
      auth.uid()
    ) on conflict (workspace_id, version) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists flbp_workspace_state_capture_version on public.workspace_state;
create trigger flbp_workspace_state_capture_version
after insert or update on public.workspace_state
for each row execute function public.flbp_workspace_state_capture_version();

-- Public mirrors are fenced as well. service_role backups remain allowed.
create or replace function public.flbp_public_workspace_primary_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text := coalesce(auth.role(), '');
  v_plane record;
  v_workspace_id text;
  v_backup_context text := coalesce(current_setting('flbp.local_backup_context', true), '');
begin
  v_workspace_id := case when tg_op = 'DELETE' then old.workspace_id else new.workspace_id end;
  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || v_workspace_id));
  select mode, node_id, epoch, lease_expires_at into v_plane
  from public.flbp_data_plane where workspace_id = v_workspace_id;
  if found and v_plane.mode in ('local', 'recovery') then
    if v_role <> 'service_role'
      or v_backup_context <> (v_workspace_id || ':' || v_plane.node_id || ':' || v_plane.epoch::text)
    then
      if v_plane.mode = 'local' and v_plane.lease_expires_at > now() then
        raise exception 'FLBP_LOCAL_PRIMARY: il server locale è il nodo di scrittura attivo';
      end if;
      raise exception 'FLBP_DATA_PLANE_RECOVERY: leadership locale scaduta; mirror pubblico protetto';
    end if;
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists flbp_public_workspace_primary_guard on public.public_workspace_state;
create trigger flbp_public_workspace_primary_guard
before insert or update or delete on public.public_workspace_state
for each row execute function public.flbp_public_workspace_primary_guard();

drop trigger if exists flbp_public_workspace_live_primary_guard on public.public_workspace_live;
create trigger flbp_public_workspace_live_primary_guard
before insert or update or delete on public.public_workspace_live
for each row execute function public.flbp_public_workspace_primary_guard();

create table if not exists public.flbp_local_operation_log (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  node_id text not null,
  primary_epoch bigint,
  operation_id text not null,
  local_version bigint not null,
  operation_kind text not null,
  payload jsonb not null,
  created_at timestamptz not null,
  received_at timestamptz not null default now(),
  applied_at timestamptz,
  unique (workspace_id, operation_id),
  unique (workspace_id, primary_epoch, local_version)
);

alter table public.flbp_local_operation_log enable row level security;
revoke all on table public.flbp_local_operation_log from public, anon, authenticated;

create or replace function public.flbp_local_operation_log_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plane record;
begin
  if auth.role() <> 'service_role' then raise exception 'service_role richiesta'; end if;
  if new.primary_epoch is null then raise exception 'primary_epoch mancante'; end if;

  if tg_op = 'UPDATE' and (
    new.workspace_id is distinct from old.workspace_id
    or new.node_id is distinct from old.node_id
    or new.primary_epoch is distinct from old.primary_epoch
    or new.operation_id is distinct from old.operation_id
    or new.local_version is distinct from old.local_version
    or new.operation_kind is distinct from old.operation_kind
    or new.payload is distinct from old.payload
    or new.created_at is distinct from old.created_at
  ) then
    raise exception 'FLBP_APPEND_ONLY: i dati di una operazione journal non sono modificabili';
  end if;

  -- Usa lo stesso lock dello switch. Un upload partito prima di activate viene
  -- completato e incluso nel controllo high-water; uno partito dopo attende e
  -- viene respinto perché l'epoch è ormai cambiato.
  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || new.workspace_id));
  select mode, node_id, epoch into v_plane
  from public.flbp_data_plane
  where workspace_id = new.workspace_id;
  if not found or v_plane.mode <> 'local'
    or v_plane.node_id <> new.node_id or v_plane.epoch <> new.primary_epoch
  then
    raise exception 'FLBP_EPOCH_FENCED: operazione journal rifiutata';
  end if;
  return new;
end;
$$;

drop trigger if exists flbp_local_operation_log_guard on public.flbp_local_operation_log;
create trigger flbp_local_operation_log_guard
before insert or update on public.flbp_local_operation_log
for each row execute function public.flbp_local_operation_log_guard();

-- Conferma l'intero batch oppure non conferma nulla. Evita che un
-- on-conflict-ignore faccia sparire dal disco un'operazione che in realtà si è
-- scontrata con un operation_id/versione remota differente.
create or replace function public.flbp_local_append_operations(
  p_workspace_id text,
  p_node_id text,
  p_epoch bigint,
  p_operations jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id text := coalesce(nullif(trim(p_workspace_id), ''), 'default');
  v_node_id text := nullif(trim(coalesce(p_node_id, '')), '');
  v_plane record;
  v_cloud record;
  v_cursor bigint := 0;
  v_entry jsonb;
  v_operation_id text;
  v_local_version bigint;
  v_operation_kind text;
  v_payload jsonb;
  v_created_at timestamptz;
  v_existing record;
  v_confirmed integer := 0;
  v_inserted integer := 0;
  v_idempotent integer := 0;
  v_covered integer := 0;
begin
  if auth.role() <> 'service_role' then raise exception 'service_role richiesta'; end if;
  if v_node_id is null then raise exception 'node_id mancante'; end if;
  if coalesce(p_epoch, 0) <= 0 then raise exception 'primary_epoch mancante'; end if;
  if jsonb_typeof(coalesce(p_operations, '[]'::jsonb)) <> 'array' then
    raise exception 'p_operations deve essere un array JSON';
  end if;
  if jsonb_array_length(coalesce(p_operations, '[]'::jsonb)) > 100 then
    raise exception 'Massimo 100 operazioni per batch';
  end if;

  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || v_workspace_id));
  select * into v_plane
  from public.flbp_data_plane
  where workspace_id = v_workspace_id
  for update;
  if not found or v_plane.mode not in ('local', 'recovery')
    or v_plane.node_id <> v_node_id or v_plane.epoch <> p_epoch
  then
    raise exception 'FLBP_EPOCH_FENCED: journal rifiutato, il nodo non possiede più questo epoch';
  end if;

  select version, last_operation_id into v_cloud
  from public.workspace_state
  where workspace_id = v_workspace_id
  for update;
  v_cursor := coalesce(v_cloud.version, 0);
  select greatest(v_cursor, coalesce(max(local_version), v_cursor)) into v_cursor
  from public.flbp_local_operation_log
  where workspace_id = v_workspace_id and primary_epoch = p_epoch;

  for v_entry in
    select value from jsonb_array_elements(coalesce(p_operations, '[]'::jsonb)) with ordinality
    order by ordinality
  loop
    v_operation_id := trim(coalesce(v_entry->>'operation_id', ''));
    v_local_version := coalesce((v_entry->>'local_version')::bigint, 0);
    v_operation_kind := trim(coalesce(v_entry->>'operation_kind', ''));
    v_payload := coalesce(v_entry->'payload', '{}'::jsonb);
    v_created_at := (v_entry->>'created_at')::timestamptz;

    if v_operation_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$' then
      raise exception 'FLBP_INVALID_OPERATION: operation_id non valido';
    end if;
    if v_local_version <= 0 then raise exception 'FLBP_INVALID_OPERATION: local_version non valida'; end if;
    if v_operation_kind not in ('workspace-snapshot', 'match-result') then
      raise exception 'FLBP_INVALID_OPERATION: operation_kind non supportato';
    end if;
    if jsonb_typeof(v_payload) <> 'object' then
      raise exception 'FLBP_INVALID_OPERATION: payload deve essere un oggetto JSON';
    end if;

    select * into v_existing
    from public.flbp_local_operation_log
    where workspace_id = v_workspace_id and operation_id = v_operation_id;
    if found then
      if v_existing.node_id is distinct from v_node_id
        or v_existing.primary_epoch is distinct from p_epoch
        or v_existing.local_version is distinct from v_local_version
        or v_existing.operation_kind is distinct from v_operation_kind
        or v_existing.payload is distinct from v_payload
        or v_existing.created_at is distinct from v_created_at
      then
        raise exception 'FLBP_OPERATION_COLLISION: operation_id % associato a dati differenti', v_operation_id;
      end if;
      v_idempotent := v_idempotent + 1;
      v_confirmed := v_confirmed + 1;
      continue;
    end if;

    -- Un backup completo più recente rende superflui i record precedenti. La
    -- versione esattamente uguale è coperta solo se il suo operation_id è lo
    -- stesso registrato nello snapshot canonico.
    if v_local_version < coalesce(v_cloud.version, 0) then
      v_covered := v_covered + 1;
      v_confirmed := v_confirmed + 1;
      continue;
    end if;
    if v_local_version = coalesce(v_cloud.version, 0) then
      if v_operation_id <> coalesce(v_cloud.last_operation_id, '') then
        raise exception 'FLBP_OPERATION_COLLISION: versione cloud % associata a un’altra operazione', v_local_version;
      end if;
      v_covered := v_covered + 1;
      v_confirmed := v_confirmed + 1;
      continue;
    end if;

    if v_local_version <> v_cursor + 1 then
      raise exception 'FLBP_JOURNAL_GAP: attesa versione %, trovata %', v_cursor + 1, v_local_version;
    end if;

    insert into public.flbp_local_operation_log(
      workspace_id, node_id, primary_epoch, operation_id,
      local_version, operation_kind, payload, created_at
    ) values (
      v_workspace_id, v_node_id, p_epoch, v_operation_id,
      v_local_version, v_operation_kind, v_payload, v_created_at
    );
    v_cursor := v_local_version;
    v_inserted := v_inserted + 1;
    v_confirmed := v_confirmed + 1;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'confirmed', v_confirmed,
    'inserted', v_inserted,
    'idempotent', v_idempotent,
    'covered_by_snapshot', v_covered,
    'high_water_version', v_cursor
  );
end;
$$;

-- Scrittura cloud Admin idempotente. Il nome v2 permette un rollout senza
-- interrompere per qualche minuto i client ancora collegati alla RPC legacy.
-- Una risposta persa può essere ritentata con lo stesso operation_id; se nel
-- frattempo il DB è avanzato, il retry diventa un conflitto e non un overwrite.
create or replace function public.flbp_admin_push_workspace_state_v2(
  p_workspace_id text,
  p_state jsonb,
  p_public_state jsonb,
  p_base_updated_at timestamptz,
  p_force boolean,
  p_lease_holder text,
  p_operation_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id text := nullif(trim(coalesce(p_workspace_id, '')), '');
  v_operation_id text := trim(coalesce(p_operation_id, ''));
  v_current public.workspace_state%rowtype;
  v_has_current boolean := false;
  v_current_public_state jsonb;
  v_history record;
  v_next_updated_at timestamptz := clock_timestamp();
  v_next_version bigint;
begin
  if v_workspace_id is null then raise exception 'Workspace non valido'; end if;
  if not public.flbp_is_admin() then raise exception 'Accesso admin richiesto'; end if;
  if v_operation_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$' then
    raise exception 'FLBP_INVALID_OPERATION: operation_id non valido';
  end if;

  perform public.flbp_admin_assert_write_lease(v_workspace_id, p_lease_holder);
  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || v_workspace_id));
  insert into public.workspaces(id) values (v_workspace_id) on conflict (id) do nothing;

  select * into v_current
  from public.workspace_state
  where workspace_id = v_workspace_id
  for update;
  v_has_current := found;
  select state into v_current_public_state
  from public.public_workspace_state
  where workspace_id = v_workspace_id
  for update;

  if v_has_current and v_current.last_operation_id = v_operation_id then
    if v_current.state is distinct from coalesce(p_state, '{}'::jsonb)
      or coalesce(v_current_public_state, '{}'::jsonb) is distinct from coalesce(p_public_state, '{}'::jsonb)
    then
      raise exception 'FLBP_OPERATION_COLLISION: operation_id già associato a dati differenti';
    end if;
    return jsonb_build_object(
      'ok', true, 'idempotent', true,
      'updated_at', v_current.updated_at,
      'version', v_current.version,
      'operation_id', v_operation_id
    );
  end if;

  select version, state into v_history
  from public.workspace_state_versions
  where workspace_id = v_workspace_id and operation_id = v_operation_id
  order by version desc limit 1;
  if found then
    if v_history.state is distinct from coalesce(p_state, '{}'::jsonb) then
      raise exception 'FLBP_OPERATION_COLLISION: operation_id storico associato a dati differenti';
    end if;
    raise exception 'FLBP_DB_CONFLICT: operazione già applicata alla versione %, ora superata dalla versione %',
      v_history.version, v_current.version
      using detail = jsonb_build_object('updated_at', v_current.updated_at, 'version', v_current.version)::text;
  end if;

  if v_has_current and not coalesce(p_force, false) then
    if p_base_updated_at is null then
      raise exception 'FLBP_DB_CONFLICT: il DB contiene già uno snapshot Admin'
        using detail = jsonb_build_object('updated_at', v_current.updated_at, 'version', v_current.version)::text;
    end if;
    if v_current.updated_at is distinct from p_base_updated_at then
      raise exception 'FLBP_DB_CONFLICT: il DB è stato aggiornato da un altro Admin'
        using detail = jsonb_build_object('updated_at', v_current.updated_at, 'version', v_current.version)::text;
    end if;
  end if;

  if v_has_current
    and v_current.state is not distinct from coalesce(p_state, '{}'::jsonb)
    and coalesce(v_current_public_state, '{}'::jsonb) is not distinct from coalesce(p_public_state, '{}'::jsonb)
  then
    return jsonb_build_object(
      'ok', true, 'idempotent', true, 'no_change', true,
      'updated_at', v_current.updated_at,
      'version', v_current.version,
      'operation_id', v_current.last_operation_id
    );
  end if;

  insert into public.workspace_state(
    workspace_id, state, updated_at, version, last_operation_id, primary_epoch
  ) values (
    v_workspace_id, coalesce(p_state, '{}'::jsonb), v_next_updated_at,
    1, v_operation_id, null
  ) on conflict (workspace_id) do update set
    state = excluded.state,
    updated_at = excluded.updated_at,
    last_operation_id = excluded.last_operation_id,
    primary_epoch = null
  returning version into v_next_version;

  insert into public.public_workspace_state(workspace_id, state, updated_at)
  values (v_workspace_id, coalesce(p_public_state, '{}'::jsonb), v_next_updated_at)
  on conflict (workspace_id) do update set state = excluded.state, updated_at = excluded.updated_at;

  perform public.flbp_upsert_public_workspace_live(
    v_workspace_id,
    coalesce(p_public_state, '{}'::jsonb),
    v_next_updated_at
  );

  return jsonb_build_object(
    'ok', true, 'idempotent', false,
    'updated_at', v_next_updated_at,
    'version', v_next_version,
    'operation_id', v_operation_id
  );
end;
$$;

drop function if exists public.flbp_local_activate_data_plane(text, text, text, integer);
create or replace function public.flbp_local_activate_data_plane(
  p_workspace_id text,
  p_node_id text,
  p_base_url text,
  p_expected_cloud_version bigint,
  p_expected_cloud_operation_id text,
  p_expected_cloud_state jsonb,
  p_expected_public_state jsonb,
  p_expected_plane_epoch bigint,
  p_expected_recovered_version bigint,
  p_ttl_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id text := coalesce(nullif(trim(p_workspace_id), ''), 'default');
  v_node_id text := nullif(trim(coalesce(p_node_id, '')), '');
  v_base_url text := nullif(trim(coalesce(p_base_url, '')), '');
  v_ttl integer := least(greatest(coalesce(p_ttl_seconds, 60), 30), 300);
  v_current record;
  v_cloud record;
  v_public_state jsonb;
  v_journal_version bigint;
  v_epoch bigint;
  v_expires timestamptz := now() + make_interval(secs => v_ttl);
begin
  if auth.role() <> 'service_role' then raise exception 'service_role richiesta'; end if;
  if v_node_id is null then raise exception 'node_id mancante'; end if;
  if v_base_url is null or v_base_url !~ '^https://' then raise exception 'base_url HTTPS obbligatorio'; end if;

  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || v_workspace_id));
  insert into public.workspaces(id) values (v_workspace_id) on conflict (id) do nothing;
  select * into v_current from public.flbp_data_plane where workspace_id = v_workspace_id for update;
  if found and v_current.mode = 'local' and v_current.lease_expires_at > now() and v_current.node_id <> v_node_id then
    raise exception 'FLBP_LOCAL_PRIMARY: un altro nodo locale possiede già la leadership';
  end if;
  if coalesce(v_current.epoch, 0) <> coalesce(p_expected_plane_epoch, 0) then
    raise exception 'FLBP_ACTIVATION_CHANGED: epoch coordinatore cambiato durante il download';
  end if;

  select state, version, last_operation_id into v_cloud
  from public.workspace_state
  where workspace_id = v_workspace_id
  for update;
  if not found then
    raise exception 'FLBP_ACTIVATION_CHANGED: snapshot cloud assente';
  end if;
  if v_cloud.version <> coalesce(p_expected_cloud_version, 0)
    or coalesce(v_cloud.last_operation_id, '') <> coalesce(p_expected_cloud_operation_id, '')
    or v_cloud.state is distinct from coalesce(p_expected_cloud_state, '{}'::jsonb)
  then
    raise exception 'FLBP_ACTIVATION_CHANGED: snapshot privato cambiato durante il download';
  end if;

  select state into v_public_state
  from public.public_workspace_state
  where workspace_id = v_workspace_id
  for update;
  if not found then v_public_state := v_cloud.state; end if;
  if v_public_state is distinct from coalesce(p_expected_public_state, '{}'::jsonb) then
    raise exception 'FLBP_ACTIVATION_CHANGED: snapshot pubblico cambiato durante il download';
  end if;

  select max(local_version) into v_journal_version
  from public.flbp_local_operation_log
  where workspace_id = v_workspace_id
    and primary_epoch = coalesce(p_expected_plane_epoch, 0);
  v_journal_version := greatest(v_cloud.version, coalesce(v_journal_version, v_cloud.version));
  if v_journal_version <> coalesce(p_expected_recovered_version, v_cloud.version) then
    raise exception 'FLBP_ACTIVATION_CHANGED: journal locale avanzato durante il download';
  end if;
  v_epoch := coalesce(v_current.epoch, 0) + 1;

  insert into public.flbp_data_plane(workspace_id, mode, node_id, base_url, epoch, lease_expires_at, last_heartbeat_at, updated_at)
  values (v_workspace_id, 'local', v_node_id, v_base_url, v_epoch, v_expires, now(), now())
  on conflict (workspace_id) do update set
    mode = 'local', node_id = excluded.node_id, base_url = excluded.base_url,
    epoch = excluded.epoch, lease_expires_at = excluded.lease_expires_at,
    last_heartbeat_at = excluded.last_heartbeat_at, updated_at = now();

  return jsonb_build_object(
    'ok', true, 'mode', 'local', 'epoch', v_epoch,
    'lease_expires_at', v_expires,
    'cloud_version', v_cloud.version,
    'recovered_version', v_journal_version
  );
end;
$$;

create or replace function public.flbp_local_heartbeat_data_plane(
  p_workspace_id text,
  p_node_id text,
  p_epoch bigint,
  p_ttl_seconds integer default 60
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ttl integer := least(greatest(coalesce(p_ttl_seconds, 60), 30), 300);
  v_expires timestamptz := now() + make_interval(secs => v_ttl);
  v_rows integer := 0;
begin
  if auth.role() <> 'service_role' then raise exception 'service_role richiesta'; end if;
  update public.flbp_data_plane set
    lease_expires_at = v_expires, last_heartbeat_at = now(), updated_at = now()
  where workspace_id = p_workspace_id and mode = 'local'
    and node_id = p_node_id and epoch = p_epoch;
  get diagnostics v_rows = row_count;
  return jsonb_build_object('ok', true, 'accepted', v_rows = 1, 'epoch', p_epoch, 'lease_expires_at', v_expires);
end;
$$;

create or replace function public.flbp_local_backup_data_plane(
  p_workspace_id text,
  p_node_id text,
  p_epoch bigint,
  p_state jsonb,
  p_public_state jsonb,
  p_version bigint,
  p_operation_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plane record;
  v_cloud record;
  v_now timestamptz := now();
begin
  if auth.role() <> 'service_role' then raise exception 'service_role richiesta'; end if;
  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || p_workspace_id));
  select * into v_plane from public.flbp_data_plane
  where workspace_id = p_workspace_id for update;
  if not found or v_plane.mode not in ('local', 'recovery')
    or v_plane.node_id <> p_node_id or v_plane.epoch <> p_epoch
  then
    raise exception 'FLBP_EPOCH_FENCED: backup rifiutato, il nodo non possiede più questo epoch';
  end if;
  perform set_config(
    'flbp.local_backup_context',
    p_workspace_id || ':' || p_node_id || ':' || p_epoch::text,
    true
  );

  select version, last_operation_id into v_cloud
  from public.workspace_state
  where workspace_id = p_workspace_id
  for update;
  if found and coalesce(p_version, 0) < v_cloud.version then
    raise exception 'FLBP_DB_CONFLICT: backup locale versione % precedente alla versione cloud %', p_version, v_cloud.version;
  end if;
  if found and coalesce(p_version, 0) = v_cloud.version
    and coalesce(p_operation_id, '') <> coalesce(v_cloud.last_operation_id, '')
  then
    raise exception 'FLBP_DB_CONFLICT: la versione % è già associata a un’altra operazione', p_version;
  end if;

  insert into public.workspace_state (
    workspace_id, state, updated_at, version, last_operation_id, primary_epoch
  ) values (
    p_workspace_id, coalesce(p_state, '{}'::jsonb), v_now,
    greatest(coalesce(p_version, 1), 1), p_operation_id, p_epoch
  ) on conflict (workspace_id) do update set
    state = excluded.state,
    updated_at = excluded.updated_at,
    version = excluded.version,
    last_operation_id = excluded.last_operation_id,
    primary_epoch = excluded.primary_epoch;

  insert into public.public_workspace_state(workspace_id, state, updated_at)
  values (p_workspace_id, coalesce(p_public_state, '{}'::jsonb), v_now)
  on conflict (workspace_id) do update set state = excluded.state, updated_at = excluded.updated_at;

  insert into public.public_workspace_live(workspace_id, state, updated_at)
  values (p_workspace_id, coalesce(p_public_state, '{}'::jsonb), v_now)
  on conflict (workspace_id) do update set state = excluded.state, updated_at = excluded.updated_at;

  update public.flbp_data_plane set last_backup_at = v_now, updated_at = v_now
  where workspace_id = p_workspace_id and node_id = p_node_id and epoch = p_epoch;

  return jsonb_build_object('ok', true, 'updated_at', v_now, 'version', p_version, 'epoch', p_epoch);
end;
$$;

-- Backup finale e ritorno al cloud sono una singola transazione. In questo
-- modo una risposta HTTP persa può essere ritentata idempotentemente senza
-- lasciare un intervallo in cui il cloud è scrivibile ma il nodo locale crede
-- ancora di esserlo.
drop function if exists public.flbp_local_deactivate_data_plane(text, text, bigint);
create or replace function public.flbp_local_deactivate_data_plane(
  p_workspace_id text,
  p_node_id text,
  p_epoch bigint,
  p_state jsonb,
  p_public_state jsonb,
  p_version bigint,
  p_operation_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plane record;
  v_backup jsonb;
  v_now timestamptz := now();
begin
  if auth.role() <> 'service_role' then raise exception 'service_role richiesta'; end if;
  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || p_workspace_id));
  select * into v_plane
  from public.flbp_data_plane
  where workspace_id = p_workspace_id
  for update;
  if not found then
    raise exception 'FLBP_EPOCH_FENCED: coordinatore assente';
  end if;

  if v_plane.mode = 'cloud' and v_plane.epoch = p_epoch then
    return jsonb_build_object(
      'ok', true, 'deactivated', true, 'idempotent', true,
      'mode', 'cloud', 'epoch', p_epoch,
      'updated_at', coalesce(v_plane.last_backup_at, v_plane.updated_at),
      'version', p_version
    );
  end if;

  if v_plane.mode not in ('local', 'recovery')
    or v_plane.node_id <> p_node_id or v_plane.epoch <> p_epoch
  then
    raise exception 'FLBP_EPOCH_FENCED: disattivazione rifiutata, leadership cambiata';
  end if;

  v_backup := public.flbp_local_backup_data_plane(
    p_workspace_id, p_node_id, p_epoch,
    p_state, p_public_state, p_version, p_operation_id
  );

  update public.flbp_data_plane set
    mode = 'cloud', node_id = null, base_url = null,
    lease_expires_at = null, last_backup_at = v_now, updated_at = v_now
  where workspace_id = p_workspace_id and epoch = p_epoch;

  return jsonb_build_object(
    'ok', true, 'deactivated', true, 'idempotent', false,
    'mode', 'cloud', 'epoch', p_epoch,
    'updated_at', coalesce(v_backup->>'updated_at', v_now::text),
    'version', p_version
  );
end;
$$;

create or replace function public.flbp_resolve_data_plane(p_workspace_id text default 'default')
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_plane record;
begin
  select * into v_plane from public.flbp_data_plane where workspace_id = p_workspace_id;
  if not found or v_plane.mode = 'cloud' then
    return jsonb_build_object('mode', 'cloud', 'epoch', coalesce(v_plane.epoch, 0));
  end if;
  if v_plane.mode = 'local' and v_plane.lease_expires_at > now() then
    return jsonb_build_object(
      'mode', 'local', 'base_url', v_plane.base_url, 'epoch', v_plane.epoch,
      'lease_expires_at', v_plane.lease_expires_at
    );
  end if;
  return jsonb_build_object(
    'mode', 'recovery', 'epoch', v_plane.epoch,
    'reason', 'local_lease_expired', 'last_backup_at', v_plane.last_backup_at
  );
end;
$$;

-- Failover distruttivo solo esplicito: viene usato esclusivamente quando il
-- PC locale non è recuperabile e la lease è già scaduta. L'epoch avanza per
-- impedire a quel processo, se riappare, di pubblicare operazioni vecchie.
create or replace function public.flbp_admin_force_cloud_failover(
  p_workspace_id text default 'default',
  p_expected_epoch bigint default 0,
  p_confirmation text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id text := coalesce(nullif(trim(p_workspace_id), ''), 'default');
  v_plane record;
  v_new_epoch bigint;
  v_cloud_version bigint := 0;
  v_journal_version bigint := 0;
begin
  if not public.flbp_is_admin() then raise exception 'Accesso admin richiesto'; end if;
  if p_confirmation <> 'FAILOVER CLOUD CON POSSIBILE PERDITA' then
    raise exception 'Conferma failover non valida';
  end if;

  perform pg_advisory_xact_lock(hashtext('flbp_data_plane:' || v_workspace_id));
  select * into v_plane
  from public.flbp_data_plane
  where workspace_id = v_workspace_id
  for update;
  if not found then
    return jsonb_build_object('ok', true, 'mode', 'cloud', 'epoch', 0, 'idempotent', true);
  end if;
  if v_plane.mode = 'cloud' and v_plane.epoch = p_expected_epoch + 1 then
    return jsonb_build_object(
      'ok', true, 'mode', 'cloud', 'epoch', v_plane.epoch,
      'idempotent', true, 'last_backup_at', v_plane.last_backup_at
    );
  end if;
  if v_plane.epoch <> p_expected_epoch then
    raise exception 'FLBP_EPOCH_FENCED: epoch cambiato; aggiorna lo stato prima del failover';
  end if;
  if v_plane.mode = 'local' and v_plane.lease_expires_at > now() then
    raise exception 'FLBP_LOCAL_PRIMARY: il PC locale risulta ancora attivo; usa la disattivazione normale';
  end if;

  select coalesce(max(version), 0) into v_cloud_version
  from public.workspace_state
  where workspace_id = v_workspace_id;
  select coalesce(max(local_version), v_cloud_version) into v_journal_version
  from public.flbp_local_operation_log
  where workspace_id = v_workspace_id and primary_epoch = v_plane.epoch;
  if v_journal_version > v_cloud_version then
    raise exception 'FLBP_RECOVERY_JOURNAL_PENDING: il journal remoto arriva alla versione %, lo snapshot cloud solo alla %; usa un server sostitutivo per riprodurlo prima del failover', v_journal_version, v_cloud_version;
  end if;

  v_new_epoch := v_plane.epoch + 1;
  update public.flbp_data_plane set
    mode = 'cloud', node_id = null, base_url = null,
    epoch = v_new_epoch, lease_expires_at = null, updated_at = now()
  where workspace_id = v_workspace_id;

  return jsonb_build_object(
    'ok', true, 'mode', 'cloud', 'epoch', v_new_epoch,
    'idempotent', false, 'last_backup_at', v_plane.last_backup_at,
    'warning', 'Le operazioni rimaste solo sul PC locale non sono incluse.'
  );
end;
$$;

create or replace function public.flbp_admin_list_workspace_versions(
  p_workspace_id text default 'default',
  p_limit integer default 50
)
returns table(id bigint, version bigint, operation_id text, primary_epoch bigint, state_bytes bigint, checksum text, created_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.flbp_is_admin() then raise exception 'Accesso admin richiesto'; end if;
  return query
  select v.id, v.version, v.operation_id, v.primary_epoch, v.state_bytes, v.checksum, v.created_at
  from public.workspace_state_versions v
  where v.workspace_id = p_workspace_id
  order by v.version desc
  limit least(greatest(coalesce(p_limit, 50), 1), 200);
end;
$$;

create or replace function public.flbp_admin_get_workspace_version(p_version_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_row record;
begin
  if not public.flbp_is_admin() then raise exception 'Accesso admin richiesto'; end if;
  select * into v_row from public.workspace_state_versions where id = p_version_id;
  if not found then raise exception 'Versione non trovata'; end if;
  return jsonb_build_object(
    'id', v_row.id, 'workspace_id', v_row.workspace_id, 'version', v_row.version,
    'operation_id', v_row.operation_id, 'created_at', v_row.created_at, 'state', v_row.state
  );
end;
$$;

revoke all on function public.flbp_local_activate_data_plane(text, text, text, bigint, text, jsonb, jsonb, bigint, bigint, integer) from public, anon, authenticated;
revoke all on function public.flbp_local_append_operations(text, text, bigint, jsonb) from public, anon, authenticated;
revoke all on function public.flbp_admin_push_workspace_state_v2(text, jsonb, jsonb, timestamptz, boolean, text, text) from public, anon;
revoke all on function public.flbp_local_heartbeat_data_plane(text, text, bigint, integer) from public, anon, authenticated;
revoke all on function public.flbp_local_deactivate_data_plane(text, text, bigint, jsonb, jsonb, bigint, text) from public, anon, authenticated;
revoke all on function public.flbp_local_backup_data_plane(text, text, bigint, jsonb, jsonb, bigint, text) from public, anon, authenticated;
revoke all on function public.flbp_admin_force_cloud_failover(text, bigint, text) from public, anon;
grant execute on function public.flbp_local_activate_data_plane(text, text, text, bigint, text, jsonb, jsonb, bigint, bigint, integer) to service_role;
grant execute on function public.flbp_local_append_operations(text, text, bigint, jsonb) to service_role;
grant execute on function public.flbp_admin_push_workspace_state_v2(text, jsonb, jsonb, timestamptz, boolean, text, text) to authenticated, service_role;
grant execute on function public.flbp_local_heartbeat_data_plane(text, text, bigint, integer) to service_role;
grant execute on function public.flbp_local_deactivate_data_plane(text, text, bigint, jsonb, jsonb, bigint, text) to service_role;
grant execute on function public.flbp_local_backup_data_plane(text, text, bigint, jsonb, jsonb, bigint, text) to service_role;
grant execute on function public.flbp_admin_force_cloud_failover(text, bigint, text) to authenticated;
revoke insert, update, delete on public.flbp_local_operation_log from service_role;
grant select on public.flbp_local_operation_log to service_role;
grant usage, select on sequence public.flbp_local_operation_log_id_seq to service_role;
grant select on public.workspace_state_versions to service_role;

revoke all on function public.flbp_resolve_data_plane(text) from public;
grant execute on function public.flbp_resolve_data_plane(text) to anon, authenticated, service_role;

revoke all on function public.flbp_admin_list_workspace_versions(text, integer) from public, anon;
revoke all on function public.flbp_admin_get_workspace_version(bigint) from public, anon;
grant execute on function public.flbp_admin_list_workspace_versions(text, integer) to authenticated;
grant execute on function public.flbp_admin_get_workspace_version(bigint) to authenticated;

-- Seed a recoverable baseline for workspaces that already existed.
insert into public.workspace_state_versions (
  workspace_id, version, operation_id, primary_epoch, state,
  state_bytes, checksum, created_at, created_by
)
select ws.workspace_id, ws.version, ws.last_operation_id, ws.primary_epoch, ws.state,
       octet_length(ws.state::text), md5(ws.state::text), ws.updated_at, null
from public.workspace_state ws
on conflict (workspace_id, version) do nothing;
