import { applyDraftIntegrationChanges, listDraftIntegrationChanges } from '../../services/draftIntegrationRecovery';
import { coerceAppState } from '../../services/storageService';

const check = (value: unknown, message: string) => { if (!value) throw new Error(message); };
const equal = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);
const example = () => {
  const database = coerceAppState({
    logo: 'confirmed-logo', playerAliases: { old: 'confirmed-player' },
    tournamentHistory: [{ id: 'edition', name: 'Torneo 05/09/2026', startDate: '2026-09-05', type: 'round_robin',
      teams: [{ id: 'team', name: 'Nome aggiornato remoto' }], matches: [{ id: 'match', scoreA: 10, scoreB: 8, played: true }] }],
    hallOfFame: [{ id: 'existing', tournamentId: 'edition', tournamentName: 'Torneo 05/09/2026', type: 'winner', playerNames: ['Demo'], year: '2026', sourceAutoGenerated: false }],
    integrationsScorers: [{ id: 'scorer', sourceTournamentId: 'edition', source: 'Torneo 05/09/2026', points: 42 }],
  });
  const draft = structuredClone(database);
  draft.tournamentHistory[0].name = 'XIV Torneo Beer Pong';
  draft.tournamentHistory[0].matches![0].scoreB = 0;
  draft.logo = 'stale-logo';
  draft.playerAliases = {};
  draft.hallOfFame.push({ id: 'new-title', tournamentId: 'manual_cup', tournamentName: 'Coppa dei Campioni',
    type: 'winner', teamName: 'Squadra demo', playerNames: ['Uno', 'Due'], year: '2026', sourceType: 'manual', sourceTournamentDate: '2026-09-06' });
  return { database, draft };
};

export const registerDraftIntegrationRecoveryCases = (define: (name: string, run: () => void) => void) => {
  define('selected recovery adds a manual title and renames the edition without restoring stale results', () => {
    const { database, draft } = example();
    const before = JSON.stringify({ database, draft });
    const changes = listDraftIntegrationChanges(draft, database);
    check(changes.length === 2, 'Only the title and edition name should be proposed');
    const next = applyDraftIntegrationChanges(draft, database, changes.map(change => change.key));
    check(next.hallOfFame.some(entry => entry.id === 'new-title'), 'New title retained');
    check(next.tournamentHistory[0].name === 'XIV Torneo Beer Pong', 'Archive name updated');
    check(next.hallOfFame.find(entry => entry.id === 'existing')?.tournamentName === 'XIV Torneo Beer Pong', 'Linked title updated');
    check(next.integrationsScorers[0].sourceLabel === 'XIV Torneo Beer Pong', 'Linked scorer label updated');
    check(equal(next.tournamentHistory[0].matches, database.tournamentHistory[0].matches), 'Confirmed results must survive');
    check(equal(next.tournamentHistory[0].teams, database.tournamentHistory[0].teams), 'Confirmed teams must survive');
    check(next.logo === database.logo && equal(next.playerAliases, database.playerAliases), 'Other DB data must survive');
    check(JSON.stringify({ database, draft }) === before, 'Preview inputs must remain immutable');
  });
  define('selected recovery changes only checked items and never adds a title twice', () => {
    const { database, draft } = example();
    const next = applyDraftIntegrationChanges(draft, database, ['title:new-title']);
    check(next.tournamentHistory[0].name === database.tournamentHistory[0].name, 'Unchecked rename must not run');
    check(listDraftIntegrationChanges(draft, next).every(change => change.kind !== 'add-title'), 'A saved title must not be offered again');
    const renamed = applyDraftIntegrationChanges(draft, database, ['rename:edition']);
    check(renamed.hallOfFame.length === database.hallOfFame.length, 'Unchecked title must not be added');
  });
  define('selected recovery refuses stale choices and empty selection', () => {
    const { database, draft } = example();
    for (const keys of [[], ['title:missing']]) {
      let failed = false;
      try { applyDraftIntegrationChanges(draft, database, keys); } catch { failed = true; }
      check(failed, 'The review must be valid and explicit');
    }
  });
  define('selected recovery excludes derived awards, ambiguous ids, live renames and title replacements', () => {
    const { database, draft } = example();
    draft.hallOfFame.push({ ...draft.hallOfFame.at(-1)!, id: 'generated', sourceAutoGenerated: true });
    draft.hallOfFame.push({ ...draft.hallOfFame.at(-2)! });
    draft.hallOfFame[0].playerNames = ['Bozza obsoleta'];
    database.tournament = { ...database.tournamentHistory[0], id: 'live', name: 'Live confermato' };
    draft.tournament = { ...database.tournament, name: 'Live bozza' };
    database.integrationsScorers.push({ id: 'scorer-only', name: 'Demo', sourceTournamentId: 'scorer-only', sourceLabel: 'Edizione confermata', points: 1, games: 1, soffi: 0 });
    draft.integrationsScorers.push({ ...database.integrationsScorers.at(-1)!, sourceLabel: 'Etichetta obsoleta' });
    const changes = listDraftIntegrationChanges(draft, database);
    check(changes.length === 1 && changes[0].kind === 'rename-edition', 'Only the unambiguous archive rename is offered');
  });
};
