import type { AppState } from '../../services/storageService';
import { coerceAppState, syncTournamentAwardsToHallOfFame } from '../../services/storageService';
import type { HallOfFameEntry, IntegrationScorerEntry, Match, TournamentData } from '../../types';
import { getPlayerKey, isU25 } from '../../services/playerIdentity';
import { buildPlayerProfileSnapshot, getHallOfFamePlayerRefs } from '../../services/playerDataProvenance';
import { reassignHallOfFameEntry } from '../../services/hallOfFameAdmin';
import { updatePlayerProfileIdentity } from '../../services/playerProfileAdmin';
import { sanitizeAppStateForPublic } from '../../services/supabaseRest';
import { hasCountedPlayerStats } from '../../services/matchUtils';
import { countedIntegrations, listEditions, publicEditionHistory, rankEditionScorers, replaceEditionScorers, validateEditionAwards } from '../../services/editionData';
import { renameTournamentInState } from '../../services/tournamentRename';
import { parseScorersRows, readScorersFile } from '../../services/scorersImport';
import { scoringRankIndex } from '../../services/awardRules';
import { getXLSX } from '../../services/lazyXlsx';

const check = (ok: unknown, message: string) => { if (!ok) throw new Error(message); };
const empty = (): AppState => ({ teams: [], matches: [], tournament: null, tournamentMatches: [], tournamentHistory: [], hallOfFame: [], integrationsScorers: [], playerAliases: {}, logo: '' });
const award = (patch: Partial<HallOfFameEntry> = {}): HallOfFameEntry => ({ id: 'mvp-only', tournamentId: 'manual_edition', tournamentName: 'Coppa Storica', sourceTournamentDate: '2019-07-12', year: '2019', type: 'mvp', playerNames: ['Rossi Mario'], playerBirthDate: '1994-07-13', playerId: getPlayerKey('Rossi Mario', '1994-07-13'), sourceType: 'manual', sourceAutoGenerated: false, ...patch });
const scorer = (name: string, games: number, points: number, soffi = 0): IntegrationScorerEntry => ({ id: name, name, birthDate: '1994-07-13', games, points, soffi });

export const registerEditionManagementCases = (define: (name: string, run: () => void) => void) => {
    define('U25 uses exact age on tournament date, including the 26th birthday and invalid dates', () => {
        check(isU25('2000-07-13', '2026-07-12'), 'Still 25 before birthday');
        check(!isU25('2000-07-13', '2026-07-13'), 'No longer U25 on 26th birthday');
        check(isU25('1994-07-13', '2019-07-12'), 'Historical eligibility must not depend on today');
        check(!isU25('2027-01-01', '2026-01-01'), 'Future birth date is ineligible');
        check(!isU25('2000-07-13', '') && !isU25(undefined, '2026-07-12'), 'Missing reference or identity is ineligible');
    });
    define('finished-only and played-only matches contribute to awards; unfinished rows do not', () => {
        const team = { id: 'team', name: 'Team', player1: 'Rossi Mario', player1BirthDate: '2000-07-13', player2: '' };
        const matches: Match[] = [
            { id: 'finished', teamAId: 'team', scoreA: 0, scoreB: 0, played: false, status: 'finished', stats: [{ teamId: 'team', playerName: 'Rossi Mario', canestri: 5, soffi: 2 }] },
            { id: 'played', teamAId: 'team', scoreA: 0, scoreB: 0, played: true, status: 'scheduled', stats: [{ teamId: 'team', playerName: 'Rossi Mario', canestri: 4, soffi: 1 }] },
            { id: 'draft', scoreA: 0, scoreB: 0, played: false, status: 'playing', stats: [{ teamId: 'team', playerName: 'Rossi Mario', canestri: 99, soffi: 99 }] },
        ];
        check(matches.filter(hasCountedPlayerStats).length === 2, 'Exactly two match reports must count');
        const tournament = { id: 't', name: 'T', type: 'round_robin', teams: [team], startDate: '2026-07-12', config: { advancingPerGroup: 0 }, matches } as TournamentData;
        const entries = syncTournamentAwardsToHallOfFame([], tournament, matches);
        check(entries.find(row => row.type === 'top_scorer')?.value === 9, 'Both completed representations must count');
        check(entries.some(row => row.type === 'top_scorer_u25'), 'Age must use tournament date');
        check(!syncTournamentAwardsToHallOfFame([], { ...tournament, startDate: '2026-07-13' }, matches).some(row => row.type.endsWith('_u25')), 'Birthday must change eligibility');
        check(entries.find(row => row.type === 'top_scorer')?.playerBirthDate === '2000-07-13', 'Automatic titles retain identity');
    });
    define('imported scoring awards use fewer games, preserve exact ties and aggregate repeated player rows', () => {
        const rows = [scorer('A', 5, 20, 10), scorer('B', 3, 20, 10), scorer('C', 3, 20, 10), scorer('D', 0, 99, 99)];
        check(rankEditionScorers(empty(), rows, '2019-07-12', 'points').map(row => row.name).join() === 'B,C', 'Fewer games wins; exact ties are retained');
        check(rankEditionScorers(empty(), rows, '2019-07-12', 'soffi', true).map(row => row.name).join() === 'B,C', 'U25 defenders use the same rule');
        const combined = rankEditionScorers(empty(), [scorer('A', 1, 5), scorer('A', 1, 5), scorer('B', 3, 10)], '2019-07-12', 'points');
        check(combined.length === 1 && combined[0].name === 'A' && combined[0].games === 2, 'Repeated player rows aggregate before ranking');
        const standings = [{ points: 20, soffi: 10, gamesPlayed: 3 }, { points: 20, soffi: 5, gamesPlayed: 3 }, { points: 20, soffi: 2, gamesPlayed: 5 }];
        check(scoringRankIndex(standings, 1, 'points') === 0 && scoringRankIndex(standings, 2, 'points') === 2, 'Exact scoring ties display the same place');
    });
    define('an MVP-only edition survives backup, listing and rename without creating a stored tournament', () => {
        const state = { ...empty(), hallOfFame: [award()] };
        validateEditionAwards('Coppa Storica', '2019-07-12', state.hallOfFame);
        const restored = coerceAppState(JSON.parse(JSON.stringify(state)));
        const renamed = renameTournamentInState(restored, 'manual_edition', 'Coppa corretta').state;
        const summary = listEditions(renamed)[0];
        check(summary.name === 'Coppa corretta' && summary.date === '2019-07-12', 'MVP-only metadata must remain available');
        const legacy = { ...empty(), hallOfFame: [award({ sourceTournamentDate: null as any }), award({ id: 'dated', sourceTournamentDate: '12/07/2019' })] };
        check(listEditions(legacy)[0].date === '2019-07-12', 'Nullable legacy metadata must not hide a date stored on another title');
        check(renamed.tournamentHistory.length === 0 && publicEditionHistory(renamed)[0].matches?.length === 0, 'No stored tournament or fake matches');
        check(buildPlayerProfileSnapshot(renamed, award().playerId!)?.totalTitles === 1, 'The title must count immediately');
        let duplicateBlocked = false;
        try { validateEditionAwards('Coppa', '2019-07-12', [award(), award({ id: 'duplicate' })]); } catch { duplicateBlocked = true; }
        check(duplicateBlocked, 'A player cannot receive the same award twice in one edition');
    });
    define('manual champions keep both identities through backup, reassignment and profile correction', () => {
        const dates = ['1994-07-13', '1995-01-04'];
        const winner = award({ type: 'winner', playerNames: ['Rossi Mario', 'Bianchi Luca'], playerIds: [getPlayerKey('Rossi Mario', dates[0]), getPlayerKey('Bianchi Luca', dates[1])], playerBirthDates: dates, playerId: undefined, playerBirthDate: undefined, teamName: 'Campioni' });
        const state = coerceAppState(JSON.parse(JSON.stringify({ ...empty(), hallOfFame: [winner] })));
        const refs = getHallOfFamePlayerRefs(state, state.hallOfFame[0]);
        check(refs.map(row => row.playerId).join() === winner.playerIds!.join(), 'Both champion IDs survive backup');
        const reassigned = reassignHallOfFameEntry(state, { entryId: winner.id, playerSlotIndex: 1, nextPlayerName: 'Bianchi Luca', nextPlayerBirthDate: '1996-01-04' }).state;
        check(reassigned.hallOfFame[0].playerIds?.[0] === winner.playerIds![0], 'Reassignment preserves the other champion');
        check(getHallOfFamePlayerRefs(reassigned, reassigned.hallOfFame[0])[1].playerId.endsWith('1996-01-04'), 'Same-name different-birthday reassignment works');
        const corrected = updatePlayerProfileIdentity(state, { currentPlayerId: winner.playerIds![1], nextPlayerName: 'Bianchi Lucio', nextBirthDate: dates[1] });
        check(corrected.hallOfFame[0].playerNames[1] === 'Bianchi Lucio' && corrected.hallOfFame[0].playerNames[0] === 'Rossi Mario', 'Profile correction reaches the second champion');
    });
    define('edition imports replace their previous rows and count in annual and tournament views without duplicates', () => {
        const state = { ...empty(), hallOfFame: [award()], integrationsScorers: [scorer('External', 1, 4)] };
        const imported = [scorer('Rossi Mario', 4, 20, 2)];
        state.integrationsScorers = replaceEditionScorers(state, 'manual_edition', 'Coppa Storica', '2019-07-12', imported);
        state.integrationsScorers = replaceEditionScorers(state, 'manual_edition', 'Coppa Storica', '2019-07-12', imported);
        check(countedIntegrations(state).length === 2, 'A second import replaces the edition rows');
        check(countedIntegrations(state, '2019').length === 1 && countedIntegrations(state, '2020').length === 0, 'Annual filter selects only attributable rows');
        const match: Match = { id: 'm', played: false, status: 'finished', scoreA: 1, scoreB: 0, stats: [{ teamId: 't', playerName: 'Rossi Mario', canestri: 20, soffi: 2 }] };
        const withResults = { ...state, tournamentHistory: [{ id: 'manual_edition', name: 'Coppa', startDate: '2019-07-12', teams: [], config: {}, type: 'round_robin', matches: [match] } as TournamentData] };
        check(countedIntegrations(withResults).length === 1, 'Recorded player statistics suppress the equivalent linked import');
        let blocked = false;
        try { replaceEditionScorers(withResults, 'manual_edition', 'Coppa', '2019-07-12', imported); } catch { blocked = true; }
        check(blocked, 'Import must not overwrite a scored tournament');
    });
    define('manual ex aequo awards all survive archive resynchronization', () => {
        const t = { id: 'manual_edition', name: 'Coppa', type: 'round_robin', startDate: '2019-07-12', teams: [], config: {} } as TournamentData;
        const manual = [award({ id: 'a', type: 'top_scorer', manuallyEdited: true }), award({ id: 'b', type: 'top_scorer', playerNames: ['B'], manuallyEdited: true })];
        check(syncTournamentAwardsToHallOfFame(manual, t, []).filter(row => row.type === 'top_scorer').length === 2, 'Sync must not collapse exact ties');
    });
    define('public snapshots preserve tournament U25 while removing private champion identities', () => {
        const state = empty();
        state.tournamentHistory = [{ id: 't', name: 'T', startDate: '2019-07-12', type: 'round_robin', teams: [{ id: 'a', name: 'A', player1: 'Mario', player2: '', player1BirthDate: '1994-07-13' }], config: {} } as TournamentData];
        state.hallOfFame = [award({ playerIds: ['private_id'], playerBirthDates: ['1994-07-13'] })];
        state.integrationsScorers = [{ ...scorer('Mario', 4, 20), sourceTournamentId: 't' }];
        const safe = sanitizeAppStateForPublic(state) as unknown as AppState;
        const twice = sanitizeAppStateForPublic(safe) as any;
        check(!JSON.stringify(safe).includes('1994-07-13') && !JSON.stringify(safe).includes('private_id'), 'No date or private player ID may leak');
        check((safe.tournamentHistory[0].teams[0] as any).player1U25 === true && twice.tournamentHistory[0].teams[0].player1U25 === true, 'Tournament eligibility survives repeated sanitization');
        check(safe.integrationsScorers?.[0].tournamentU25 === true && twice.integrationsScorers[0].tournamentU25 === true, 'Imported player eligibility survives repeated sanitization');
    });
    define('the shared CSV and spreadsheet row parser rejects negative or fractional statistics', () => {
        const parsed = parseScorersRows([{ Cognome: 'Rossi', Nome: 'Mario', DataNascita: '13/07/1994', Partite: '4', Canestri: '20', Soffi: '2' }], 'file.csv');
        check(parsed.length === 1 && parsed[0].birthDate === '1994-07-13' && parsed[0].games === 4, 'Shared column aliases parse the complete row');
        for (const value of ['-2', '1.5', '1,5', 'abc']) {
            let blocked = false;
            try { parseScorersRows([{ Name: 'Mario', Games: '4', Points: value }], 'bad.csv'); } catch { blocked = true; }
            check(blocked, `Invalid total must not be silently rewritten: ${value}`);
        }
    });
    define('the file reader imports UTF-8 CSV names, dates and statistics without dropping rows', async () => {
        const csv = '\uFEFFNome;Cognome;DataNascita;Partite;Canestri;Soffi\nMario;Rossi;13/07/1994;4;20;2\nLuca;Bianchi;04/01/1995;3;20;2\n';
        const rows = await readScorersFile(new File([csv], 'edizione.csv', { type: 'text/csv' }));
        check(rows.length === 2 && rows[0].name === 'Rossi Mario' && rows[1].birthDate === '1995-01-04', 'Both CSV rows keep identity and totals');
        check(rankEditionScorers(empty(), rows, '2019-07-12', 'points')[0].name === 'Bianchi Luca', 'The imported file uses the match-count tie breaker');
    });
    define('Excel date cells retain the calendar birth date when importing scorers', async () => {
        const XLSX = await getXLSX();
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet([{ Nome: 'Mario', Cognome: 'Rossi', DataNascita: new Date(1994, 6, 13), Partite: 4, Canestri: 20, Soffi: 2 }], { cellDates: true }), 'Marcatori');
        const bytes = XLSX.write(workbook, { type: 'array', bookType: 'xlsx', cellDates: true });
        const rows = await readScorersFile(new File([bytes], 'edizione.xlsx'));
        check(rows.length === 1 && rows[0].birthDate === '1994-07-13' && rows[0].points === 20, 'A real Excel date cell must not become a serial, a locale-dependent string or the previous day');
    });
};
