import React from 'react';
import { createRoot } from 'react-dom/client';
import { FantaTeamBuilder } from '../../components/fantabeerpong/FantaTeamBuilder';
import { DataTab, type DataTabProps } from '../../components/admin/tabs/DataTab';
import { requestDraftNavigation } from '../../services/draftNavigationGuard';
import type { AppState } from '../../services/storageService';
import { getPlayerKey } from '../../services/playerIdentity';
import { draftFixture, useTranslation } from './draftProtectionFixtures';
import '../../styles.css';

if (!import.meta.env.DEV) throw new Error('Development fixture only');
const noop = () => {};
const mode = new URLSearchParams(location.search).get('mode') || 'fanta';
sessionStorage.setItem('flbp_admin_data_main_section', 'integrations');

const Fixture = () => {
  const { t } = useTranslation();
  const [destination, setDestination] = React.useState('editor');
  const [state, setState] = React.useState<AppState>({ teams: [], matches: [], tournament: null, tournamentHistory: [], tournamentMatches: [], logo: '', playerAliases: {}, integrationsScorers: [], hallOfFame: [{
    id: 'fixture-award', year: '2020', tournamentId: 'fixture-edition', tournamentName: 'Edizione demo',
    sourceTournamentDate: '2020-07-12', type: 'mvp', playerNames: ['Rossi Mario'], playerBirthDate: '2000-07-13',
    playerId: getPlayerKey('Rossi Mario', '2000-07-13'), sourceType: 'manual', sourceAutoGenerated: false,
  }] });
  const [tab, setTab] = React.useState<DataTabProps['integrationsSubTab']>('tournaments');
  const commitAdminStateDurably = async (next: AppState) => {
    draftFixture.commitAttempts++;
    const ok = await new Promise<boolean>(resolve => { draftFixture.pendingCommit = resolve; });
    draftFixture.pendingCommit = null;
    if (!ok) throw new Error('Conferma non ricevuta: bozza conservata');
    return next;
  };
  const props = {
    state, setState, commitAdminStateDurably, t, integrationsSubTab: tab, setIntegrationsSubTab: setTab,
    renameTournamentEdition: async () => {}, dataSubTab: 'integrations', setDataSubTab: noop,
    setDataSelectedTournamentId: noop, resetCreateArchiveWizard: noop, aliasesSearch: '', setAliasesSearch: noop,
    aliasToolSelections: {}, setAliasToolSelections: noop, buildProfilesIndex: () => new Map(),
    scorersImportWarnings: [], setScorersImportWarnings: noop, scorersFileRef: React.useRef(null),
  } as unknown as DataTabProps;
  return <main className="mx-auto max-w-6xl space-y-4 p-4">
    {mode === 'fanta' ? <>
      <button onClick={() => setDestination(value => value === 'editor' ? 'outside' : 'editor')}>Monta/smonta builder fixture</button>
      {destination === 'editor' && <FantaTeamBuilder onBack={() => { draftFixture.backCalls++; }} onOpenRules={noop} />}
    </> : <>
      <button onClick={() => { void requestDraftNavigation(() => setDestination('outside')); }}>Uscita SPA fixture</button>
      {destination === 'editor' ? <DataTab {...props} /> : <p>Destination outside</p>}
      <output aria-label="Saved state">{JSON.stringify(state.hallOfFame.map(row => row.tournamentName))}</output>
    </>}
  </main>;
};
createRoot(document.getElementById('root')!).render(<Fixture />);
