import type { AppState } from './storageService';
import type { HallOfFameEntry } from '../types';
import { getPlayerKey, normalizeBirthDateInput, pickStoredPlayerIdentityValue } from './playerIdentity';

export interface HallOfFameEntryOrigin {
  sourceType: 'archived_tournament' | 'manual';
  sourceTournamentId?: string;
  sourceTournamentName?: string;
  sourceMatchId?: string | null;
  sourceAutoGenerated: boolean;
  manuallyEdited: boolean;
  reassignable: boolean;
  deletable: boolean;
}

export interface DeleteHallOfFameEntryResult {
  state: AppState;
  removedEntry: HallOfFameEntry;
}

export interface ReassignHallOfFameEntryInput {
  entryId: string;
  nextPlayerName: string;
  nextPlayerBirthDate?: string;
  nextPlayerYoB?: number;
  playerSlotIndex?: number | null;
}

export interface ReassignHallOfFameEntryResult {
  state: AppState;
  entry: HallOfFameEntry;
}

export const getHallOfFameEntryOrigin = (entry: HallOfFameEntry): HallOfFameEntryOrigin => {
  const sourceType =
    entry.sourceType ||
    (String(entry.tournamentId || '').startsWith('manual_') ? 'manual' : 'archived_tournament');

  return {
    sourceType,
    sourceTournamentId: entry.sourceTournamentId || entry.tournamentId || undefined,
    sourceTournamentName: entry.sourceTournamentName || entry.tournamentName || undefined,
    sourceMatchId: entry.sourceMatchId ?? null,
    sourceAutoGenerated: !!entry.sourceAutoGenerated,
    manuallyEdited: !!entry.manuallyEdited,
    reassignable: true,
    deletable: true,
  };
};

export const deleteHallOfFameEntry = (state: AppState, entryId: string): DeleteHallOfFameEntryResult => {
  const current = (state.hallOfFame || []).find((entry) => entry.id === entryId);
  if (!current) {
    throw new Error("Record dell'Albo d'Oro non trovato.");
  }

  return {
    state: {
      ...state,
      hallOfFame: (state.hallOfFame || []).filter((entry) => entry.id !== entryId),
    },
    removedEntry: current,
  };
};

export const reassignHallOfFameEntry = (
  state: AppState,
  input: ReassignHallOfFameEntryInput
): ReassignHallOfFameEntryResult => {
  const nextName = String(input.nextPlayerName || '').trim();
  if (!nextName) {
    throw new Error('Inserisci il giocatore di destinazione.');
  }

  const index = (state.hallOfFame || []).findIndex((entry) => entry.id === input.entryId);
  if (index < 0) {
    throw new Error("Record dell'Albo d'Oro non trovato.");
  }

  const current = (state.hallOfFame || [])[index];
  const nextBirthDate = normalizeBirthDateInput(input.nextPlayerBirthDate || undefined);
  if (input.nextPlayerBirthDate && !nextBirthDate) {
    throw new Error('La data di nascita non è valida. Usa gg/mm/aaaa oppure il calendario.');
  }
  const nextPlayerId = getPlayerKey(
    nextName,
    pickStoredPlayerIdentityValue(nextBirthDate, Number.isFinite(input.nextPlayerYoB as number) ? Number(input.nextPlayerYoB) : undefined)
  );

  let updated: HallOfFameEntry;
  if (current.type === 'winner') {
    const playerNames = Array.isArray(current.playerNames) ? [...current.playerNames] : [];
    const slotIndex = Math.max(
      0,
      Math.min(
        playerNames.length > 0 ? playerNames.length - 1 : 0,
        Number.isFinite(input.playerSlotIndex as number) ? Number(input.playerSlotIndex) : 0
      )
    );
    const previousName = playerNames[slotIndex] || '';
    const previousPlayerId = previousName ? getPlayerKey(previousName, 'ND') : null;
    if (previousName.trim().toLowerCase() === nextName.trim().toLowerCase()) {
      throw new Error('Il titolo è già assegnato a questo giocatore.');
    }
    if (!playerNames.length) playerNames.push(nextName);
    else playerNames[slotIndex] = nextName;
    updated = {
      ...current,
      playerNames,
      reassignedFromPlayerId: previousPlayerId,
      manuallyEdited: true,
    };
  } else {
    const currentPlayerId = String(current.playerId || '').trim();
    if (currentPlayerId && currentPlayerId === nextPlayerId) {
      throw new Error('Il titolo è già assegnato a questo giocatore.');
    }
    updated = {
      ...current,
      playerId: nextPlayerId,
      playerBirthDate: nextBirthDate,
      playerNames: [nextName],
      reassignedFromPlayerId: currentPlayerId || null,
      manuallyEdited: true,
    };
  }

  const nextHallOfFame = [...(state.hallOfFame || [])];
  nextHallOfFame[index] = updated;

  return {
    state: {
      ...state,
      hallOfFame: nextHallOfFame,
    },
    entry: updated,
  };
};
