export interface MatchStats {
    teamId: string;
    playerName: string;
    canestri: number;
    soffi: number;
}

export type RefereeReportAuditSource = 'admin' | 'referee';

export interface RefereeReportAuditEntry {
    id: string;
    matchId: string;
    source: RefereeReportAuditSource;
    refereeName: string;
    savedAt: string;
    scoreA: number;
    scoreB: number;
    scoresByTeam?: Record<string, number>;
    stats?: MatchStats[];
}

export interface Match {
    id: string;
    teamAId?: string;
    teamBId?: string;
    /** Optional multi-team participant list (used for group tie-break multi-team matches). */
    teamIds?: string[];
    /** Optional per-team scores for multi-team matches. Keys are teamId values from teamIds. */
    scoresByTeam?: Record<string, number>;
    scoreA: number;
    scoreB: number;
    played: boolean;
    status: 'scheduled' | 'playing' | 'finished';
    stats?: MatchStats[];
    round?: number;
    code?: string;
    phase?: 'groups' | 'bracket';
    groupName?: string;
    roundName?: string;
    orderIndex?: number;
    hidden?: boolean;
    /** True when the match exists only to represent a BYE auto-advance. */
    isBye?: boolean;
    /** True for extra playoff matches used to resolve group ties. */
    isTieBreak?: boolean;
    /** Target score for simulation/gameplay (default 10). For group tie-break usually 1. */
    targetScore?: number;
    /** Live-only audit trail for reports saved by Admin or referees. Stripped from archived tournaments. */
    refereeReportAudit?: RefereeReportAuditEntry[];
    refereeReportFinalId?: string;
    refereeReportSource?: RefereeReportAuditSource;
    refereeReportAuthorName?: string;
    refereeReportSavedAt?: string;
}

export type TournamentMatch = Match;

export interface Team {
    id: string;
    name: string;
    player1: string;
    player2?: string;
    player1YoB?: number;
    player2YoB?: number;
    player1BirthDate?: string;
    player2BirthDate?: string;
    player1IsReferee?: boolean;
    player2IsReferee?: boolean;
    isReferee?: boolean;
    createdAt?: number;
    /** Optional: can be present in persisted state for special placeholders (e.g. BYE). */
    hidden?: boolean;
    /** Optional: can be present in persisted state for special placeholders (e.g. BYE). */
    isBye?: boolean;
}

export interface Group {
    id: string;
    name: string;
    teams: Team[];
    /** Optional: used to tag the final round-robin stage. */
    stage?: 'groups' | 'final';
}

export type FinalRoundRobinTopTeams = 4 | 8;

export interface FinalRoundRobinConfig {
    enabled: boolean;
    topTeams: FinalRoundRobinTopTeams;
    /** Set to true when the final stage has been activated in a live tournament. */
    activated?: boolean;
}

export interface TournamentConfig {
    advancingPerGroup: number;
    /** Optional: enables an extra final round-robin stage (activated at runtime). */
    finalRoundRobin?: FinalRoundRobinConfig;
    /**
     * Optional: number of concurrent tables used to group matches into "turni".
     * Backward-compatible: when missing, UI falls back to local defaults.
     */
    refTables?: number;
}

export interface TournamentData {
    id: string;
    name: string;
    type: 'elimination' | 'groups_elimination' | 'round_robin';
    startDate: string;
    teams: Team[];
    rounds?: Match[][];
    groups?: Group[];
    matches?: Match[];
    config: TournamentConfig;
    /** Optional list of referee display names enabled for Referees Area in the live tournament. */
    refereesRoster?: string[];
    /** Optional: live-only password required to access Referees Area for the current live tournament. */
    refereesPassword?: string;
    /** Optional auth version bump used to invalidate referee sessions after a password reset. */
    refereesAuthVersion?: string;
    isManual?: boolean;
    includeU25Awards?: boolean;
}

export interface HallOfFameEntry {
    id: string;
    year: string;
    tournamentId: string;
    tournamentName: string;
    type: 'winner' | 'mvp' | 'top_scorer' | 'defender' | 'top_scorer_u25' | 'defender_u25';
    teamName?: string;
    playerNames: string[];
    value?: number;
    playerId?: string;
    playerBirthDate?: string;
    sourceType?: 'archived_tournament' | 'manual';
    sourceTournamentId?: string;
    sourceTournamentName?: string;
    sourceTournamentDate?: string;
    sourceMatchId?: string | null;
    sourceAutoGenerated?: boolean;
    reassignedFromPlayerId?: string | null;
    manuallyEdited?: boolean;
}

// Integrazioni manuali per classifica generale marcatori (fuori dai tornei archiviati)
export interface IntegrationScorerEntry {
    id: string;
    name: string;
    yob?: number;
    birthDate?: string;
    games: number;
    points: number;
    soffi: number;
    createdAt?: number;
    source?: string;
    sourceType?: 'manual_integration';
    sourceTournamentId?: string | null;
    sourceLabel?: string;
    teamName?: string;
}

export interface PlayerTitleSourceRow {
    id: string;
    entryId: string;
    playerId: string;
    playerName: string;
    playerSlotIndex?: number | null;
    year: string;
    tournamentId: string;
    tournamentName: string;
    type: HallOfFameEntry['type'];
    teamName?: string;
    playerNames: string[];
    value?: number;
    sourceType: 'archived_tournament' | 'manual';
    sourceTournamentId?: string;
    sourceTournamentName?: string;
    sourceTournamentDate?: string;
    sourceMatchId?: string | null;
    sourceAutoGenerated: boolean;
    manuallyEdited: boolean;
    editable: boolean;
    reassignable: boolean;
    deletable: boolean;
}

export interface PlayerContributionSourceRow {
    id: string;
    playerId: string;
    playerName: string;
    sourceType: 'archived_tournament_match' | 'manual_integration';
    tournamentId?: string | null;
    tournamentName?: string | null;
    tournamentYear?: string | null;
    matchId?: string | null;
    teamId?: string | null;
    teamName?: string | null;
    canestri: number;
    soffi: number;
    games: number;
    sourceLabel?: string | null;
    manuallyAdded: boolean;
}

export interface PlayerAliasRelationRow {
    id: string;
    fromKey: string;
    toKey: string;
    direction: 'incoming' | 'outgoing';
    otherKey: string;
    otherLabel: string;
}

export interface PlayerProfileSnapshot {
    playerId: string;
    displayName: string;
    yobLabel: string;
    aliasCount: number;
    totalTitles: number;
    totalCanestri: number;
    totalSoffi: number;
    hasArchivedData: boolean;
    hasManualData: boolean;
    badges: Array<'archivio' | 'manuale' | 'alias_attivo'>;
    titles: PlayerTitleSourceRow[];
    contributions: PlayerContributionSourceRow[];
    aliases: PlayerAliasRelationRow[];
}

export interface PlayerStats {
    id: string;
    name: string;
    teamName: string;
    gamesPlayed: number;
    wins?: number;
    losses?: number;
    winRate?: number;
    points: number;
    soffi: number;
    avgPoints: number;
    avgSoffi: number;
    /**
     * BirthDate-first identity used for player merge and U25 classification when available.
     */
    birthDate?: string;
    yob?: number;
    /**
     * Optional: used by DB-backed public leaderboard.
     * If present, it should be treated as the authoritative Under-25 classification.
     */
    u25?: boolean;
    /**
     * Optional 2-digit YoB label (e.g. "98"). Used only for disambiguation in UI.
     * Full YoB remains non-public.
     */
    yobLabel?: string;
}

export const TV_PROJECTIONS = ['groups', 'groups_bracket', 'bracket', 'scorers'] as const;
export type TvProjection = typeof TV_PROJECTIONS[number];
