import { archiveTournamentV2, coerceAppState, syncArchivedHistoryToHallOfFame, syncTournamentAwardsToHallOfFame, type AppState } from '../../services/storageService';
import type { HallOfFameEntry, IntegrationScorerEntry, Match, Team, TournamentData } from '../../types';
import { removeArchivedTournamentDeep } from '../../services/archiveCascadeDelete';
import { buildPlayerProfileSnapshot, getAliasRemovalImpact, removePlayerAliasMapping } from '../../services/playerDataProvenance';
import { deleteHallOfFameEntry, getHallOfFameEntryOrigin, reassignHallOfFameEntry } from '../../services/hallOfFameAdmin';
import { generateTournamentStructure } from '../../services/tournamentEngine';

const makeBirthDate = (year: number) => `${year}-01-01`;

const makeTeam = (id: string, name: string, p1: string, y1: number, p2: string, y2: number): Team => ({
  id,
  name,
  player1: p1,
  player1YoB: y1,
  player1BirthDate: makeBirthDate(y1),
  player2: p2,
  player2YoB: y2,
  player2BirthDate: makeBirthDate(y2),
});

const makeMatch = (id: string, teamAId: string, teamBId: string, stats: Match['stats']): Match => ({
  id,
  teamAId,
  teamBId,
  scoreA: 10,
  scoreB: 8,
  played: true,
  status: 'finished',
  phase: 'groups',
  groupName: 'Girone A',
  orderIndex: 1,
  stats,
});

const tournament: TournamentData = {
  id: 'arch_2025',
  name: 'FLBP 2025',
  type: 'round_robin',
  startDate: '2025-12-20',
  teams: [
    makeTeam('T1', 'Beer Killers', 'Rossi Mario', 1998, 'Bianchi Luca', 1999),
    makeTeam('T2', 'Foam Masters', 'Verdi Paolo', 2001, 'Neri Gino', 2000),
  ],
  matches: [
    makeMatch('m1', 'T1', 'T2', [
      { teamId: 'T1', playerName: 'Rossi Mario', canestri: 6, soffi: 2 },
      { teamId: 'T1', playerName: 'Bianchi Luca', canestri: 4, soffi: 1 },
      { teamId: 'T2', playerName: 'Verdi Paolo', canestri: 5, soffi: 0 },
      { teamId: 'T2', playerName: 'Neri Gino', canestri: 3, soffi: 2 },
    ]),
  ],
  groups: [
    {
      id: 'g1',
      name: 'Girone A',
      teams: [
        makeTeam('T1', 'Beer Killers', 'Rossi Mario', 1998, 'Bianchi Luca', 1999),
        makeTeam('T2', 'Foam Masters', 'Verdi Paolo', 2001, 'Neri Gino', 2000),
      ],
    },
  ],
  config: { advancingPerGroup: 2 },
};

const hallOfFame: HallOfFameEntry[] = [
  {
    id: 'arch_2025_winner',
    year: '2025',
    tournamentId: 'arch_2025',
    tournamentName: 'FLBP 2025',
    type: 'winner',
    teamName: 'Beer Killers',
    playerNames: ['Rossi Mario', 'Bianchi Luca'],
    sourceType: 'archived_tournament',
    sourceTournamentId: 'arch_2025',
    sourceTournamentName: 'FLBP 2025',
    sourceAutoGenerated: true,
  },
  {
    id: 'arch_2025_top_scorer',
    year: '2025',
    tournamentId: 'arch_2025',
    tournamentName: 'FLBP 2025',
    type: 'top_scorer',
    playerNames: ['Rossi Mario'],
    playerId: 'rossi_mario_1998-01-01',
    playerBirthDate: '1998-01-01',
    value: 6,
    sourceType: 'archived_tournament',
    sourceTournamentId: 'arch_2025',
    sourceTournamentName: 'FLBP 2025',
    sourceAutoGenerated: true,
  },
  {
    id: 'manual_mvp_2024',
    year: '2024',
    tournamentId: 'manual_1',
    tournamentName: 'Winter Cup',
    type: 'mvp',
    playerNames: ['Rossi Mario'],
    playerId: 'rossi_mario_1998-01-01',
    playerBirthDate: '1998-01-01',
    sourceType: 'manual',
    sourceTournamentId: 'manual_1',
    sourceTournamentName: 'Winter Cup',
    sourceAutoGenerated: false,
    manuallyEdited: true,
  },
];

const integrationsScorers: IntegrationScorerEntry[] = [
  {
    id: 'sc_1',
    name: 'Rossi Mario',
    yob: 1998,
    birthDate: '1998-01-01',
    games: 3,
    points: 9,
    soffi: 1,
    source: 'manual.csv',
    sourceType: 'manual_integration',
    sourceLabel: 'manual.csv',
    createdAt: Date.now(),
  },
];

const baseState: AppState = {
  __schemaVersion: 1,
  teams: [],
  matches: [],
  tournament: null,
  tournamentMatches: [],
  tournamentHistory: [tournament],
  logo: '',
  hallOfFame,
  integrationsScorers,
  playerAliases: {
    rossi_mario_nd: 'rossi_mario_1998-01-01',
  },
};

const cases: Array<{ name: string; run: () => void }> = [];
const defineCase = (name: string, run: () => void) => cases.push({ name, run });

const assertEqual = (actual: unknown, expected: unknown, message?: string) => {
  if (!Object.is(actual, expected)) {
    throw new Error(message || `Expected ${JSON.stringify(expected)}, received ${JSON.stringify(actual)}`);
  }
};

const assertOk = (value: unknown, message?: string) => {
  if (!value) {
    throw new Error(message || 'Expected truthy value.');
  }
};

defineCase('deep delete removes archived tournament and linked hall of fame entries with impact summary', () => {
  const result = removeArchivedTournamentDeep(baseState, 'arch_2025');
  assertEqual(result.state.tournamentHistory.length, 0);
  assertEqual(result.state.hallOfFame.length, 1);
  assertEqual(result.summary.removedTournament, 1);
  assertEqual(result.summary.removedHallOfFameEntries, 2);
  assertEqual(result.summary.removedMatchStats, 4);
  assertOk(result.summary.affectedPlayers >= 4);
});

defineCase('player profile snapshot exposes titles, archived stats, manual stats and aliases together', () => {
  const profile = buildPlayerProfileSnapshot(baseState, 'rossi_mario_1998-01-01');
  if (!profile) throw new Error('Expected player profile snapshot.');
  assertEqual(profile.totalTitles, 3);
  assertEqual(profile.totalCanestri, 15);
  assertEqual(profile.totalSoffi, 3);
  assertEqual(profile.aliasCount, 1);
  assertOk(profile.badges.includes('archivio'));
  assertOk(profile.badges.includes('manuale'));
  assertOk(profile.badges.includes('alias_attivo'));
});

defineCase('hall of fame origin classifies manual and archived entries', () => {
  const archivedOrigin = getHallOfFameEntryOrigin(hallOfFame[0]);
  const manualOrigin = getHallOfFameEntryOrigin(hallOfFame[2]);
  assertEqual(archivedOrigin.sourceType, 'archived_tournament');
  assertEqual(archivedOrigin.sourceAutoGenerated, true);
  assertEqual(manualOrigin.sourceType, 'manual');
  assertEqual(manualOrigin.manuallyEdited, true);
});

defineCase('reassign hall of fame entry updates player and marks manual edit provenance', () => {
  const result = reassignHallOfFameEntry(baseState, {
    entryId: 'arch_2025_top_scorer',
    nextPlayerName: 'Verdi Paolo',
    nextPlayerBirthDate: '2001-01-01',
  });
  const entry = result.state.hallOfFame.find((row) => row.id === 'arch_2025_top_scorer');
  if (!entry) throw new Error('Expected reassigned entry.');
  assertEqual(entry.playerId, 'verdi_paolo_2001-01-01');
  assertEqual(entry.playerNames[0], 'Verdi Paolo');
  assertEqual(entry.manuallyEdited, true);
});

defineCase('delete hall of fame entry removes only the selected record', () => {
  const result = deleteHallOfFameEntry(baseState, 'manual_mvp_2024');
  assertEqual(result.state.hallOfFame.length, 2);
  assertOk(!result.state.hallOfFame.some((row) => row.id === 'manual_mvp_2024'));
});

defineCase('alias removal impact highlights redistributed logical sources and removal updates state', () => {
  const impact = getAliasRemovalImpact(baseState, 'rossi_mario_nd');
  assertEqual(impact.separatedProfiles, 1);
  assertOk(impact.affectedContributionRows >= 0);
  const next = removePlayerAliasMapping(baseState, 'rossi_mario_nd');
  assertEqual(Object.keys(next.playerAliases).length, 0);
});

defineCase('automatic award sync refreshes archived tournament titles while preserving manual overrides', () => {
  const manualOverride: HallOfFameEntry = {
    id: 'arch_2025_top_scorer',
    year: '2025',
    tournamentId: 'arch_2025',
    tournamentName: 'FLBP 2025',
    type: 'top_scorer',
    playerNames: ['Verdi Paolo'],
    playerId: 'verdi_paolo_2001-01-01',
    playerBirthDate: '2001-01-01',
    value: 99,
    sourceType: 'archived_tournament',
    sourceTournamentId: 'arch_2025',
    sourceTournamentName: 'FLBP 2025',
    sourceAutoGenerated: false,
    manuallyEdited: true,
  };
  const manualMvp: HallOfFameEntry = {
    id: 'arch_2025_mvp_rossi',
    year: '2025',
    tournamentId: 'arch_2025',
    tournamentName: 'FLBP 2025',
    type: 'mvp',
    playerNames: ['Rossi Mario'],
    playerId: 'rossi_mario_1998-01-01',
    playerBirthDate: '1998-01-01',
    sourceType: 'archived_tournament',
    sourceTournamentId: 'arch_2025',
    sourceTournamentName: 'FLBP 2025',
    sourceAutoGenerated: false,
    manuallyEdited: true,
  };

  const synced = syncTournamentAwardsToHallOfFame(
    [...baseState.hallOfFame.filter((entry) => entry.tournamentId !== 'arch_2025'), manualOverride, manualMvp],
    tournament,
    tournament.matches || [],
    tournament.teams || []
  );

  const topScorer = synced.find((entry) => entry.id === 'arch_2025_top_scorer');
  const winner = synced.find((entry) => entry.tournamentId === 'arch_2025' && entry.type === 'winner');
  const mvp = synced.find((entry) => entry.id === 'arch_2025_mvp_rossi');
  if (!topScorer || !winner || !mvp) throw new Error('Expected synced award entries.');

  assertEqual(topScorer.playerNames[0], 'Verdi Paolo');
  assertEqual(topScorer.manuallyEdited, true);
  assertEqual(winner.type, 'winner');
  assertEqual(mvp.type, 'mvp');
});

defineCase('live archive flow writes automatic hall of fame entries while preserving current tournament MVPs', () => {
  const liveState: AppState = {
    ...baseState,
    tournamentHistory: [],
    tournament,
    tournamentMatches: tournament.matches || [],
    hallOfFame: [
      {
        id: 'arch_2025_mvp_rossi',
        year: '2025',
        tournamentId: 'arch_2025',
        tournamentName: 'FLBP 2025',
        type: 'mvp',
        playerNames: ['Rossi Mario'],
        playerId: 'rossi_mario_1998-01-01',
        playerBirthDate: '1998-01-01',
        sourceType: 'archived_tournament',
        sourceTournamentId: 'arch_2025',
        sourceTournamentName: 'FLBP 2025',
        sourceAutoGenerated: false,
        manuallyEdited: true,
      },
    ],
  };

  const archived = archiveTournamentV2(liveState);
  assertEqual(archived.tournament, null);
  assertEqual(archived.tournamentHistory.length, 1);
  assertOk(archived.hallOfFame.some((entry) => entry.tournamentId === 'arch_2025' && entry.type === 'winner'));
  assertOk(archived.hallOfFame.some((entry) => entry.tournamentId === 'arch_2025' && entry.type === 'top_scorer'));
  assertOk(archived.hallOfFame.some((entry) => entry.tournamentId === 'arch_2025' && entry.type === 'mvp'));
});

defineCase('archived history sync backfills missing hall of fame entries for archived tournaments', () => {
  const nextHallOfFame = syncArchivedHistoryToHallOfFame({
    ...baseState,
    hallOfFame: baseState.hallOfFame.filter((entry) => entry.tournamentId !== 'arch_2025'),
  });

  assertOk(nextHallOfFame.some((entry) => entry.tournamentId === 'arch_2025' && entry.type === 'winner'));
  assertOk(nextHallOfFame.some((entry) => entry.tournamentId === 'arch_2025' && entry.type === 'top_scorer'));
});

defineCase('coerce state repairs hall of fame even for archived tournaments stored with rounds only', () => {
  const roundsOnlyTournament: TournamentData = {
    ...tournament,
    matches: [],
    rounds: [[...(tournament.matches || [])]],
  };

  const repaired = coerceAppState({
    ...baseState,
    tournamentHistory: [roundsOnlyTournament],
    hallOfFame: [],
  });

  assertOk(repaired.hallOfFame.some((entry) => entry.tournamentId === 'arch_2025' && entry.type === 'winner'));
  assertOk(repaired.hallOfFame.some((entry) => entry.tournamentId === 'arch_2025' && entry.type === 'top_scorer'));
});

defineCase('tournament generation ignores hidden and BYE teams when counting bracket matches', () => {
  const activeA = makeTeam('A', 'Alpha', 'A One', 1998, 'A Two', 1999);
  const activeB = makeTeam('B', 'Bravo', 'B One', 1998, 'B Two', 1999);
  const activeC = makeTeam('C', 'Charlie', 'C One', 1998, 'C Two', 1999);
  const hidden = { ...makeTeam('H', 'Hidden', 'H One', 1998, 'H Two', 1999), hidden: true } as Team;
  const bye = { ...makeTeam('BYE_TEAM', 'BYE Team', 'Bye One', 1998, 'Bye Two', 1999), isBye: true } as Team;

  const { tournament, matches } = generateTournamentStructure(
    [activeA, activeB, activeC, hidden, bye],
    {
      mode: 'elimination',
      tournamentName: 'Test',
    }
  );

  assertEqual(tournament.teams.length, 3);
  assertEqual(matches.filter((match) => match.phase === 'bracket').length, 3);
});

defineCase('tournament generation keeps the selected tournament date', () => {
  const activeA = makeTeam('A', 'Alpha', 'A One', 1998, 'A Two', 1999);
  const activeB = makeTeam('B', 'Bravo', 'B One', 1998, 'B Two', 1999);

  const { tournament } = generateTournamentStructure(
    [activeA, activeB],
    {
      mode: 'elimination',
      tournamentName: 'Test Date',
      startDate: '2026-07-18',
    }
  );

  assertEqual(tournament.startDate, '2026-07-18T00:00:00.000Z');
});

let failed = 0;
for (const entry of cases) {
  try {
    entry.run();
    console.log(`PASS ${entry.name}`);
  } catch (error) {
    failed += 1;
    console.error(`FAIL ${entry.name}`);
    console.error(error);
  }
}

if (failed > 0) {
  process.exitCode = 1;
} else {
  console.log(`All player data management tests passed (${cases.length}).`);
}
