import type { AppState } from '../../services/storageService';
import { coerceAppState } from '../../services/storageService';
import { stableStateSerialize } from '../../services/stableStateSerialize';
import { tryMergeRemoteStateConflict } from '../../services/stateConflictMerge';
import type { HallOfFameEntry, TournamentData } from '../../types';

const check: (condition: unknown, message: string) => asserts condition = (condition, message) => {
  if (!condition) throw new Error(message);
};
const empty = (patch: Record<string, unknown> = {}): AppState => coerceAppState(patch);
const award = (id: string): HallOfFameEntry => ({
  id,
  year: '2026',
  tournamentId: 'manual-cup',
  tournamentName: 'Coppa Integrazioni',
  type: 'mvp',
  playerNames: ['Mario Rossi'],
  sourceType: 'manual',
  sourceAutoGenerated: false,
});
const reorderKeys = <T,>(value: T): T => JSON.parse(JSON.stringify(value, (_key, current) =>
  current && typeof current === 'object' && !Array.isArray(current)
    ? Object.fromEntries(Object.entries(current).reverse())
    : current
));

export const registerStateConflictMergeCases = (define: (name: string, run: () => void) => void) => {
  define('state comparison ignores nested JSON object key order while preserving array order and deletions', () => {
    const state = { config: { enabled: true, nested: [{ id: 'one', name: 'First' }] }, names: ['A', 'B'] };
    check(stableStateSerialize(state) === stableStateSerialize(reorderKeys(state)), 'JSON object order must not create a difference');
    check(stableStateSerialize(state) !== stableStateSerialize({ ...state, names: ['B', 'A'] }), 'Array positions must remain significant');
    check(stableStateSerialize(undefined) !== stableStateSerialize(null), 'Deleting a value and setting null are different changes');
    check(stableStateSerialize({ value: undefined }) === stableStateSerialize({}), 'Optional undefined object fields follow persisted JSON semantics');
  });

  define('a local integration title merges with a remote team edit after JSON object keys are reordered', () => {
    const baseState = empty({ teams: [{ id: 'team-1', name: 'Prima', player1: 'Mario Rossi', player2: 'Luca Bianchi' }], hallOfFame: [award('existing')] });
    const localState = { ...reorderKeys(baseState), hallOfFame: [...reorderKeys(baseState.hallOfFame), award('added-locally')] };
    const remoteState = { ...baseState, teams: [{ ...baseState.teams[0], name: 'Nome aggiornato online' }] };
    const inputBefore = JSON.stringify({ baseState, localState, remoteState });
    const result = tryMergeRemoteStateConflict({ baseState, localState, remoteState });
    check(result.ok, 'An unchanged record with reordered keys must not overlap a remote edit');
    check(result.state.hallOfFame.some((entry) => entry.id === 'added-locally'), 'The local title must survive');
    check(result.state.teams[0]?.name === 'Nome aggiornato online', 'The remote edit must survive');
    check(result.mergedSlices.includes('hallOfFame') && result.mergedSlices.includes('teams'), 'Both changed collections are reported');
    check(JSON.stringify({ baseState, localState, remoteState }) === inputBefore, 'Comparing and merging must leave input snapshots intact');
  });

  define('independent additions to integration titles and scorers survive on both sides', () => {
    const baseState = empty();
    const scorer = { id: 'remote-scorer', name: 'Luca Bianchi', games: 2, points: 8, soffi: 1 };
    const result = tryMergeRemoteStateConflict({
      baseState,
      localState: { ...baseState, hallOfFame: [award('local-title')] },
      remoteState: { ...baseState, hallOfFame: [{ ...award('remote-title'), playerNames: ['Luca Bianchi'] }], integrationsScorers: [scorer] },
    });
    check(result.ok, 'Different title IDs and scorer rows are independent');
    check(result.state.hallOfFame.length === 2 && result.state.integrationsScorers[0]?.id === scorer.id, 'Every independently added record survives');
  });

  define('optional settings, schema metadata, extra fields and their deletion are preserved during conflict merge', () => {
    const baseState = empty({ __schemaVersion: 0, fantaSettings: { enabled: false, updatedAt: 'old' }, extraToRemove: { enabled: true } });
    const localState = { ...baseState, __schemaVersion: 1, fantaSettings: { enabled: true, updatedAt: 'new' }, extraLocal: { names: ['A', 'B'] } };
    delete (localState as any).extraToRemove;
    const remoteState = empty({ ...baseState, logo: 'remote-logo', extraRemote: { enabled: true } });
    const result = tryMergeRemoteStateConflict({ baseState, localState, remoteState });
    check(result.ok, 'Changes in separate state fields must merge');
    check(result.state.__schemaVersion === 1 && result.state.fantaSettings?.enabled === true, 'Optional AppState fields must keep their local edits');
    check((result.state as any).extraLocal?.names.join() === 'A,B' && (result.state as any).extraRemote?.enabled === true, 'Future fields on either side must survive');
    check(!Object.hasOwn(result.state, 'extraToRemove'), 'A local extra-field removal must remain a removal');
    check(result.state.logo === 'remote-logo', 'Merging extra fields must retain known remote changes');
  });

  define('conflicting settings and different edits to an extra field require a decision', () => {
    const baseState = empty({ fantaSettings: { enabled: false, updatedAt: 'base' }, preference: 'original' });
    const settingsConflict = tryMergeRemoteStateConflict({
      baseState,
      localState: { ...baseState, fantaSettings: { enabled: true, updatedAt: 'local' } },
      remoteState: { ...baseState, fantaSettings: { enabled: false, updatedAt: 'remote' } },
    });
    check(!settingsConflict.ok, 'Concurrent different settings edits must not silently prefer remote');
    const removal = { ...baseState };
    delete (removal as any).preference;
    const extraConflict = tryMergeRemoteStateConflict({ baseState, localState: removal, remoteState: empty({ ...baseState, preference: null }) });
    check(!extraConflict.ok, 'Removing an extra field while the remote side changes it to null is a real conflict');
  });

  define('different edits to the same integration title remain a real conflict', () => {
    const entry = award('same-title');
    const baseState = empty({ hallOfFame: [entry] });
    const result = tryMergeRemoteStateConflict({
      baseState,
      localState: { ...baseState, hallOfFame: [{ ...entry, playerNames: ['Nome locale'] }] },
      remoteState: { ...baseState, hallOfFame: [{ ...entry, playerNames: ['Nome remoto'] }] },
    });
    check(result.ok === false && result.reason === 'hallOfFame:overlap:id:same-title', 'Different assignments of one title must remain blocked');
  });

  define('removing an integration title conflicts with a concurrent edit, while an unchanged remote row allows removal', () => {
    const entry = award('removed-title');
    const baseState = empty({ hallOfFame: [entry] });
    const localState = { ...baseState, hallOfFame: [] };
    const conflict = tryMergeRemoteStateConflict({ baseState, localState, remoteState: { ...baseState, hallOfFame: [{ ...entry, playerNames: ['Nuovo vincitore'] }] } });
    check(conflict.ok === false && conflict.reason.startsWith('hallOfFame:overlap:'), 'Deletion must not discard a concurrent remote title edit');
    const safe = tryMergeRemoteStateConflict({ baseState, localState, remoteState: { ...reorderKeys(baseState), logo: 'remote-logo' } });
    check(safe.ok && safe.state.hallOfFame.length === 0 && safe.state.logo === 'remote-logo', 'An unchanged remote title permits deletion alongside independent changes');
  });

  define('future live tournament metadata survives alongside a remote edit to a different team', () => {
    const tournament = {
      id: 'live', name: 'Coppa', type: 'round_robin', startDate: '2026-09-10', config: { advancingPerGroup: 1 },
      teams: [{ id: 'team-1', name: 'Prima', player1: 'Mario', player2: 'Luca' }], groups: [], matches: [],
      extraMetadata: { label: 'base' },
    } as TournamentData;
    const baseState = empty({ tournament });
    const result = tryMergeRemoteStateConflict({
      baseState,
      localState: { ...baseState, tournament: { ...tournament, extraMetadata: { label: 'local' } } as TournamentData },
      remoteState: { ...baseState, tournament: { ...tournament, teams: [{ ...tournament.teams[0], name: 'Remota' }] } },
    });
    check(result.ok, 'Independent tournament fields must merge');
    check((result.state.tournament as any)?.extraMetadata?.label === 'local', 'Future local metadata must not silently disappear');
    check(result.state.tournament?.teams[0]?.name === 'Remota', 'The remote team edit remains present');
  });

  define('missing common base never authorizes an automatic merge', () => {
    const result = tryMergeRemoteStateConflict({ baseState: null, localState: empty({ hallOfFame: [award('local-title')] }), remoteState: empty() });
    check(result.ok === false && result.reason === 'base-state-missing', 'A merge without a common base must require comparison');
  });
};
