// Development-only component fixture. No authentication or persistence operations.
import React from 'react';
import { createRoot } from 'react-dom/client';
import { IntegrationsSubTab } from '../../components/admin/tabs/data/IntegrationsSubTab';
import type { DataTabProps } from '../../components/admin/tabs/DataTab';
import type { AppState } from '../../services/storageService';
import { dictionary } from '../../services/i18n/it';
import { renameTournamentInState } from '../../services/tournamentRename';
import { getPlayerKey } from '../../services/playerIdentity';
import '../../styles.css';

if (!import.meta.env.DEV) throw new Error('Development fixture only');
const noop = () => {};
const Fixture = () => {
    const [state, setState] = React.useState<AppState>({ teams: [], matches: [], tournament: null, tournamentHistory: [], tournamentMatches: [], logo: '', playerAliases: {}, integrationsScorers: [], hallOfFame: [
        { id: 'fixture-a', year: '2020', tournamentId: 'fixture-edition', tournamentName: 'Edizione demo', sourceTournamentDate: '2020-07-12', type: 'mvp', playerNames: ['Rossi Mario'], playerBirthDate: '2000-07-13', playerId: getPlayerKey('Rossi Mario', '2000-07-13'), sourceType: 'manual', sourceAutoGenerated: false },
        { id: 'fixture-b', year: '2020', tournamentId: 'fixture-edition', tournamentName: 'Edizione demo', sourceTournamentDate: '2020-07-12', type: 'mvp', playerNames: ['Bianchi Luca'], playerBirthDate: '1998-04-10', playerId: getPlayerKey('Bianchi Luca', '1998-04-10'), sourceType: 'manual', sourceAutoGenerated: false },
    ] });
    const [tab, setTab] = React.useState<DataTabProps['integrationsSubTab']>('tournaments');
    const props = {
        state, setState, t: (key: string) => dictionary[key] || key, integrationsSubTab: tab, setIntegrationsSubTab: setTab,
        renameTournamentEdition: async (id: string, name: string) => setState(current => renameTournamentInState(current, id, name).state),
        dataSubTab: 'integrations', setDataSubTab: noop, setDataSelectedTournamentId: noop, resetCreateArchiveWizard: noop,
        aliasesSearch: '', setAliasesSearch: noop, aliasToolSelections: {}, setAliasToolSelections: noop, buildProfilesIndex: () => new Map(),
        scorersImportWarnings: [], setScorersImportWarnings: noop, scorersFileRef: React.useRef(null),
    } as unknown as DataTabProps;
    return <main className="mx-auto max-w-6xl space-y-4 p-4"><p className="rounded-xl bg-amber-100 p-3 text-sm font-bold">Test locale con dati inventati · modifiche solo in memoria</p><IntegrationsSubTab {...props} /><output className="block rounded-xl border p-3 text-xs" aria-label="Dati di verifica">{JSON.stringify({ titles: state.hallOfFame.length, imports: state.integrationsScorers?.length, editions: [...new Set(state.hallOfFame.map(row => row.tournamentId))].length })}</output></main>;
};
createRoot(document.getElementById('root')!).render(<Fixture />);
