import type { HallOfFameEntry } from '../types';
import { getPlayerKey } from './playerIdentity';

export interface MetricAwardPlayer {
    name: string;
    yob?: number;
    birthDate?: string;
    points: number;
    soffi: number;
    games: number;
}

type MetricKey = 'points' | 'soffi';
type AwardType = 'top_scorer' | 'defender' | 'top_scorer_u25' | 'defender_u25';

const sortPlayers = (players: MetricAwardPlayer[]) =>
    players.slice().sort((a, b) => a.name.localeCompare(b.name, 'it', { sensitivity: 'base' }));

export const selectMetricAwardWinners = (players: MetricAwardPlayer[], metric: MetricKey): MetricAwardPlayer[] => {
    const eligible = (players || []).filter((p) => (p.games || 0) > 0 && (p[metric] || 0) > 0);
    if (!eligible.length) return [];

    const maxMetric = Math.max(...eligible.map((p) => p[metric] || 0));
    const tiedOnMetric = eligible.filter((p) => (p[metric] || 0) === maxMetric);
    if (tiedOnMetric.length <= 1) return sortPlayers(tiedOnMetric);

    // If totals are tied, the higher average wins.
    // With equal totals, that means fewer matches played.
    const minGames = Math.min(...tiedOnMetric.map((p) => p.games || 0));
    return sortPlayers(tiedOnMetric.filter((p) => (p.games || 0) === minGames));
};

export const buildMetricAwardEntries = (opts: {
    tournamentId: string;
    tournamentName: string;
    year: string;
    type: AwardType;
    players: MetricAwardPlayer[];
    metric: MetricKey;
}): HallOfFameEntry[] => {
    const winners = selectMetricAwardWinners(opts.players, opts.metric);
    if (!winners.length) return [];

    return winners.map((player) => {
        const playerId = getPlayerKey(player.name, player.birthDate || 'ND');
        const suffix = winners.length === 1 ? '' : `_${playerId}`;
        return {
            id: `${opts.tournamentId}_${opts.type}${suffix}`,
            year: opts.year,
            tournamentId: opts.tournamentId,
            tournamentName: opts.tournamentName,
            type: opts.type,
            playerNames: [player.name],
            value: player[opts.metric],
            playerId,
            sourceType: 'archived_tournament',
            sourceTournamentId: opts.tournamentId,
            sourceTournamentName: opts.tournamentName,
            sourceAutoGenerated: true,
            manuallyEdited: false,
        };
    });
};
