import type { HallOfFameEntry } from '../types';
import type { AppState } from './storageService';
import { listEditions } from './editionData';
import { renameTournamentInState } from './tournamentRename';

export type DraftIntegrationChange =
  | { key: string; kind: 'add-title'; entry: HallOfFameEntry }
  | { key: string; kind: 'rename-edition'; editionId: string; previousName: string; nextName: string };

/** A reviewable patch against the current DB, requiring no guessed old baseline. */
export const listDraftIntegrationChanges = (draft: AppState, database: AppState): DraftIntegrationChange[] => {
  const changes: DraftIntegrationChange[] = [];
  const storedTitleIds = new Set((database.hallOfFame || []).map(entry => entry.id));
  const draftIdCounts = new Map<string, number>();
  for (const entry of draft.hallOfFame || []) draftIdCounts.set(entry.id, (draftIdCounts.get(entry.id) || 0) + 1);
  for (const entry of draft.hallOfFame || []) {
    // Derived awards require the archived results, not a stale copied award.
    const manual = entry.sourceType === 'manual' || String(entry.tournamentId || '').startsWith('manual_');
    if (!entry.id || !entry.tournamentId || !manual || entry.sourceAutoGenerated
      || storedTitleIds.has(entry.id) || draftIdCounts.get(entry.id) !== 1) continue;
    changes.push({ key: `title:${entry.id}`, kind: 'add-title', entry });
  }
  const remoteEditions = new Map(listEditions(database).map(edition => [edition.id, edition]));
  for (const edition of listEditions(draft)) {
    const stored = remoteEditions.get(edition.id);
    if (!stored || stored.live || edition.live || (!stored.tournament && !stored.awards.length)
      || !edition.name.trim() || stored.name === edition.name) continue;
    changes.push({
      key: `rename:${edition.id}`, kind: 'rename-edition', editionId: edition.id,
      previousName: stored.name, nextName: edition.name,
    });
  }
  return changes;
};

export const applyDraftIntegrationChanges = (
  draft: AppState, database: AppState, selectedKeys: string[],
): AppState => {
  const choices = new Map(listDraftIntegrationChanges(draft, database).map(change => [change.key, change]));
  const selected = [...new Set(selectedKeys)];
  if (!selected.length) throw new Error('Seleziona almeno una modifica da recuperare.');
  if (selected.some(key => !choices.has(key))) throw new Error('Le differenze sono cambiate. Ripeti il confronto.');
  let next = structuredClone(database);
  for (const key of selected) {
    const change = choices.get(key)!;
    if (change.kind !== 'add-title') continue;
    const entry = structuredClone(change.entry);
    // When a title belongs to an existing edition, keep its confirmed label.
    // A selected rename below updates every linked label together.
    const edition = listEditions(next).find(row => row.id === entry.tournamentId);
    if (edition) {
      entry.tournamentName = edition.name;
      if (entry.sourceTournamentId === edition.id) entry.sourceTournamentName = edition.name;
    }
    next.hallOfFame = [...(next.hallOfFame || []), entry];
  }
  for (const key of selected) {
    const change = choices.get(key)!;
    if (change.kind === 'rename-edition') {
      next = renameTournamentInState(next, change.editionId, change.nextName).state;
    }
  }
  return next;
};
