// Auto-generated extension of SIM_TEAM_NAMES_200 to 400 deterministic names.
import { SIM_TEAM_NAMES_200 } from './simTeamNames200';

export const SIM_TEAM_NAMES_400: string[] = [
  ...SIM_TEAM_NAMES_200,
  // Extended variants (200)
  "LE MATUSA United",
  "OMINI DELLE BOMBE Club",
  "Eppure Team",
  "Ricci&Muscoli Crew",
  "Davattro Squad",
  "Tucu Correa Academy",
  "Sefarditi FC",
  "Buon NatAlex BC",
  "Pinco panico Brewing",
  "Sensibilità e educazione Party",
  "Splash Bros Legends",
  "Beer Angels Girls",
  "K Queens",
  "Basta Poco Sisters",
  "Rigatoni Pasta Warriors",
  "Parelli 5.4 Rebels",
  "I Miralcoolati Rockets",
  "Senza SentimIento Vikings",
  "I boccino Rangers",
  "Gli Amici di B.O.R.I.S Tigers",
  "SUPER &QUARK United",
  "Gsc Club",
  "Alcolisti ingenui Team",
  "Io e te Crew",
  "Gli Zero Mira Squad",
  "CB Academy",
  "sissignore FC",
  "I Polpi BC",
  "Schisce Brewing",
  "I PNC Party",
  "Daddy e Quaglia Legends",
  "Tranquilli ma Tossici Girls",
  "Paziente e Dottore Queens",
  "Double IPA Sisters",
  "Parappappa! Warriors",
  "I 101 sorsi Rebels",
  "Cabrones Rockets",
  "Senza lilleri non si Ler Vikings",
  "La Clio Rangers",
  "Ci vuole polso Tigers",
  "Seifuoribella United",
  "IL DUO Club",
  "TENNIS MAULINA Team",
  "I Margini Crew",
  "Northampton Squad",
  "Zinellacci Academy",
  "Grunge FC",
  "Los Mirabiliantes Dos BC",
  "Los fantasticos dos Brewing",
  "Olimpico Party",
  "Le Avvogatte Legends",
  "Le SkizzoSkizzo Girls",
  "Lagradisco Queens",
  "Le tocche Sisters",
  "I Frusi Warriors",
  "Orate Rebels",
  "ALFONSO SIGNORINi Rockets",
  "The Plow and The Show Vikings",
  "Los Pollos Hermanos Rangers",
  "Ci falciano Tigers",
  "Atletico Divano United",
  "La mattina dopo Club",
  "Perfetti sconosciuti Team",
  "Japan called Crew",
  "Tampussi Squad",
  "Dadi Academy",
  "Bonny Pizza FC",
  "ARISTOCAZZI BC",
  "Tommi in scatola Brewing",
  "Beerkenau Party",
  "Fenomeno o bluffff Legends",
  "Abu Bhari Girls",
  "Newpsie Queens",
  "Guelfi e Ghisellini Sisters",
  "Da Boe Warriors",
  "#Skizofrenia Rebels",
  "La Cappella Rockets",
  "Clickers Vikings",
  "Gli Stonfi Rangers",
  "Pinco panco panco pinco Tigers",
  "Nuanda1000 United",
  "PNC Club",
  "Odio Jo Bott Team",
  "MajinBu&Babidi Crew",
  "Tanti auguri caro Peeta Squad",
  "JLO Academy",
  "Fidanzati con una sBirra FC",
  "Fuzcaldi BC",
  "Zio Gianluca Brewing",
  "FB buongiorno Party",
  "Squadra enchantix Legends",
  "apostoli di Tognarazinger Girls",
  "Schizzo del mercoledì Queens",
  "Siam queste amo Sisters",
  "Chaos&Loathing Warriors",
  "Alex & Michele Rebels",
  "Obrigad Rockets",
  "GLI OMINI DELLE BOMBE Vikings",
  "Procioni Frocioni Rangers",
  "Delicatezza e sensibilità Tigers",
  "Satanazzi United",
  "Locals B Club",
  "Smithers&Mr.Burns Team",
  "I soci Crew",
  "Costruzione dal basso Squad",
  "Il danno e la beffa Academy",
  "Daje Roma daje FC",
  "I Testimoni di Piero BC",
  "Mai una Gioia Brewing",
  "Billeri Party",
  "I Giocabili Legends",
  "Smooth Operators Girls",
  "Il boccino Queens",
  "P.S.V. Sisters",
  "Blasco Warriors",
  "Senza quorum Rebels",
  "Igor Miti Rockets",
  "Alguer Vikings",
  "Poggiez Rangers",
  "Sti Stranieri Tigers",
  "Sbronzi a rete United",
  "Funghi Furiosi Club",
  "I piolisti Team",
  "LE MATUSA II Crew",
  "OMINI DELLE BOMBE II Squad",
  "Eppure II Academy",
  "Ricci&Muscoli II FC",
  "Davattro II BC",
  "Tucu Correa II Brewing",
  "Sefarditi II Party",
  "Buon NatAlex II Legends",
  "Pinco panico II Girls",
  "Sensibilità e educazione II Queens",
  "Splash Bros II Sisters",
  "Beer Angels II Warriors",
  "K II Rebels",
  "Basta Poco II Rockets",
  "Rigatoni Pasta II Vikings",
  "Parelli 5.4 II Rangers",
  "I Miralcoolati II Tigers",
  "Senza SentimIento II United",
  "I boccino II Club",
  "Gli Amici di B.O.R.I.S II Team",
  "SUPER &QUARK II Crew",
  "Gsc II Squad",
  "Alcolisti ingenui II Academy",
  "Io e te II FC",
  "Gli Zero Mira II BC",
  "CB II Brewing",
  "sissignore II Party",
  "I Polpi II Legends",
  "Schisce II Girls",
  "I PNC II Queens",
  "Daddy e Quaglia II Sisters",
  "Tranquilli ma Tossici II Warriors",
  "Paziente e Dottore II Rebels",
  "Double IPA II Rockets",
  "Parappappa! II Vikings",
  "I 101 sorsi II Rangers",
  "Cabrones II Tigers",
  "Senza lilleri non si Ler II United",
  "La Clio II Club",
  "Ci vuole polso II Team",
  "Seifuoribella II Crew",
  "IL DUO II Squad",
  "TENNIS MAULINA II Academy",
  "I Margini II FC",
  "Northampton II BC",
  "Zinellacci II Brewing",
  "Grunge II Party",
  "Los Mirabiliantes Dos II Legends",
  "Los fantasticos dos II Girls",
  "Olimpico II Queens",
  "Le Avvogatte II Sisters",
  "Le SkizzoSkizzo II Warriors",
  "Lagradisco II Rebels",
  "Le tocche II Rockets",
  "I Frusi II Vikings",
  "Orate II Rangers",
  "ALFONSO SIGNORINi II Tigers",
  "The Plow and The Show II United",
  "Los Pollos Hermanos II Club",
  "Ci falciano II Team",
  "Atletico Divano II Crew",
  "La mattina dopo II Squad",
  "Perfetti sconosciuti II Academy",
  "Japan called II FC",
  "Tampussi II BC",
  "Dadi II Brewing",
  "Bonny Pizza II Party",
  "ARISTOCAZZI II Legends",
  "Tommi in scatola II Girls",
  "Beerkenau II Queens",
  "Fenomeno o bluffff II Sisters",
  "Abu Bhari II Warriors",
  "Newpsie II Rebels",
  "Guelfi e Ghisellini II Rockets",
  "Da Boe II Vikings",
  "#Skizofrenia II Rangers",
  "La Cappella II Tigers",
];
